//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_SURAT_KPT.Models.ADO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DB_Surat_KPTEntities : DbContext
    {
        public DB_Surat_KPTEntities()
            : base("name=DB_Surat_KPTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_H_LETTER_EBEK_RELASI> TBL_H_LETTER_EBEK_RELASI { get; set; }
        public virtual DbSet<TBL_H_LETTER_FAKTA_INTEGRITAS> TBL_H_LETTER_FAKTA_INTEGRITAS { get; set; }
        public virtual DbSet<VW_LOGIN_USER> VW_LOGIN_USER { get; set; }
        public virtual DbSet<VW_USER_LOGIN> VW_USER_LOGIN { get; set; }
        public virtual DbSet<TBL_H_LETTER_EBEK_COI> TBL_H_LETTER_EBEK_COI { get; set; }
        public virtual DbSet<TBL_H_LETTER_EBEK> TBL_H_LETTER_EBEK { get; set; }
    
        public virtual ObjectResult<Fakta_Integritas_H_Result> Fakta_Integritas_H(string nRP)
        {
            var nRPParameter = nRP != null ?
                new ObjectParameter("NRP", nRP) :
                new ObjectParameter("NRP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Fakta_Integritas_H_Result>("Fakta_Integritas_H", nRPParameter);
        }
    
        public virtual ObjectResult<GetDataSurat_Result> GetDataSurat(string nRP)
        {
            var nRPParameter = nRP != null ?
                new ObjectParameter("NRP", nRP) :
                new ObjectParameter("NRP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDataSurat_Result>("GetDataSurat", nRPParameter);
        }
    
        public virtual ObjectResult<Getdatasurat_Fakta_integritas_Result> Getdatasurat_Fakta_integritas(string nrp)
        {
            var nrpParameter = nrp != null ?
                new ObjectParameter("Nrp", nrp) :
                new ObjectParameter("Nrp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Getdatasurat_Fakta_integritas_Result>("Getdatasurat_Fakta_integritas", nrpParameter);
        }
    
        public virtual int insert_integritas(string nO_SURAT, string nRP, string nAME, string pOSITION_ID, string dEPT_DESC, string aDDRESS, Nullable<System.DateTime> lETTER_DATE, Nullable<System.DateTime> cRE_DATE, string cRE_BY, Nullable<System.DateTime> mOD_DATE, string mOD_BY)
        {
            var nO_SURATParameter = nO_SURAT != null ?
                new ObjectParameter("NO_SURAT", nO_SURAT) :
                new ObjectParameter("NO_SURAT", typeof(string));
    
            var nRPParameter = nRP != null ?
                new ObjectParameter("NRP", nRP) :
                new ObjectParameter("NRP", typeof(string));
    
            var nAMEParameter = nAME != null ?
                new ObjectParameter("NAME", nAME) :
                new ObjectParameter("NAME", typeof(string));
    
            var pOSITION_IDParameter = pOSITION_ID != null ?
                new ObjectParameter("POSITION_ID", pOSITION_ID) :
                new ObjectParameter("POSITION_ID", typeof(string));
    
            var dEPT_DESCParameter = dEPT_DESC != null ?
                new ObjectParameter("DEPT_DESC", dEPT_DESC) :
                new ObjectParameter("DEPT_DESC", typeof(string));
    
            var aDDRESSParameter = aDDRESS != null ?
                new ObjectParameter("ADDRESS", aDDRESS) :
                new ObjectParameter("ADDRESS", typeof(string));
    
            var lETTER_DATEParameter = lETTER_DATE.HasValue ?
                new ObjectParameter("LETTER_DATE", lETTER_DATE) :
                new ObjectParameter("LETTER_DATE", typeof(System.DateTime));
    
            var cRE_DATEParameter = cRE_DATE.HasValue ?
                new ObjectParameter("CRE_DATE", cRE_DATE) :
                new ObjectParameter("CRE_DATE", typeof(System.DateTime));
    
            var cRE_BYParameter = cRE_BY != null ?
                new ObjectParameter("CRE_BY", cRE_BY) :
                new ObjectParameter("CRE_BY", typeof(string));
    
            var mOD_DATEParameter = mOD_DATE.HasValue ?
                new ObjectParameter("MOD_DATE", mOD_DATE) :
                new ObjectParameter("MOD_DATE", typeof(System.DateTime));
    
            var mOD_BYParameter = mOD_BY != null ?
                new ObjectParameter("MOD_BY", mOD_BY) :
                new ObjectParameter("MOD_BY", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insert_integritas", nO_SURATParameter, nRPParameter, nAMEParameter, pOSITION_IDParameter, dEPT_DESCParameter, aDDRESSParameter, lETTER_DATEParameter, cRE_DATEParameter, cRE_BYParameter, mOD_DATEParameter, mOD_BYParameter);
        }
    
        public virtual ObjectResult<Login_Result> Login(string nRP)
        {
            var nRPParameter = nRP != null ?
                new ObjectParameter("NRP", nRP) :
                new ObjectParameter("NRP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Login_Result>("Login", nRPParameter);
        }
    
        public virtual ObjectResult<Getdatasurat_EBEK_Result> Getdatasurat_EBEK(string nrp)
        {
            var nrpParameter = nrp != null ?
                new ObjectParameter("Nrp", nrp) :
                new ObjectParameter("Nrp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Getdatasurat_EBEK_Result>("Getdatasurat_EBEK", nrpParameter);
        }
    }
}
