//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_SURAT_KPT.Models.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_H_LETTER_EBEK_COI
    {
        public long ID { get; set; }
        public long ID_EBEK_HISTORY { get; set; }
        public bool COI_NO_1_JABATAN { get; set; }
        public bool COI_NO_1_DEPARTMENT { get; set; }
        public bool COI_NO_1_KELUARGA { get; set; }
        public bool COI_NO_2_JABATAN { get; set; }
        public bool COI_NO_2_DEPARTMENT { get; set; }
        public bool COI_NO_2_KELUARGA { get; set; }
        public Nullable<bool> COI_NO_3_JABATAN { get; set; }
        public Nullable<bool> COI_NO_3_DEPARTMENT { get; set; }
        public Nullable<bool> COI_NO_3_KELUARGA { get; set; }
        public Nullable<bool> COI_NO_4_JABATAN { get; set; }
        public Nullable<bool> COI_NO_4_DEPARTMENT { get; set; }
        public Nullable<bool> COI_NO_4_KELUARGA { get; set; }
        public Nullable<bool> COI_NO_5_JABATAN { get; set; }
        public Nullable<bool> COI_NO_5_DEPARTMENT { get; set; }
        public Nullable<bool> COI_NO_5_KELUARGA { get; set; }
    }
}
