//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_SURAT_KPT.Models.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_H_LETTER_EBEK
    {
        public long ID { get; set; }
        public string NO_SURAT { get; set; }
        public bool KELUARGA_DI_KPP_FLAG { get; set; }
        public bool KELUARGA_DI_REKANAN_KPP { get; set; }
    }
}
