//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_SURAT_KPT.Models.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_H_LETTER_FAKTA_INTEGRITAS
    {
        public long ID { get; set; }
        public string NO_SURAT { get; set; }
        public string NRP { get; set; }
        public string NAME { get; set; }
        public string POSITION_ID { get; set; }
        public string DEPT_DESC { get; set; }
        public string ADDRESS { get; set; }
        public Nullable<System.DateTime> LETTER_DATE { get; set; }
        public Nullable<System.DateTime> CRE_DATE { get; set; }
        public string CRE_BY { get; set; }
        public Nullable<System.DateTime> MOD_DATE { get; set; }
        public string MOD_BY { get; set; }
    }
}
