//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_SURAT_KPT.Models.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_LOGIN_USER
    {
        public string EMPLOYEE_ID { get; set; }
        public string NAME { get; set; }
        public string POSITION_ID { get; set; }
        public string POS_TITLE { get; set; }
        public string dstrct_code { get; set; }
        public string dept_code { get; set; }
        public string dept_desc { get; set; }
        public string alamat { get; set; }
        public string No_telp { get; set; }
    }
}
