//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_SURAT_KPT.Models.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_USER_LOGIN
    {
        public string name { get; set; }
        public string dept_code { get; set; }
        public string distrik { get; set; }
        public string NRP { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> expiredDate { get; set; }
        public string otp { get; set; }
        public string token { get; set; }
        public string device_id { get; set; }
        public Nullable<System.DateTime> loginOTPLockEndDate { get; set; }
        public string POSITION_ID { get; set; }
    }
}
