#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INTEGRASI_API_2.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_IA_PAKTA_INTEGRITAS_KPT")]
	public partial class DBPakta_IntegritasDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTBL_M_ROLE(TBL_M_ROLE instance);
    partial void UpdateTBL_M_ROLE(TBL_M_ROLE instance);
    partial void DeleteTBL_M_ROLE(TBL_M_ROLE instance);
    partial void InsertTBL_R_USER(TBL_R_USER instance);
    partial void UpdateTBL_R_USER(TBL_R_USER instance);
    partial void DeleteTBL_R_USER(TBL_R_USER instance);
    partial void InsertTBL_T_EBEK_FAMILY(TBL_T_EBEK_FAMILY instance);
    partial void UpdateTBL_T_EBEK_FAMILY(TBL_T_EBEK_FAMILY instance);
    partial void DeleteTBL_T_EBEK_FAMILY(TBL_T_EBEK_FAMILY instance);
    partial void InsertTBL_T_EBEK_MIKAD(TBL_T_EBEK_MIKAD instance);
    partial void UpdateTBL_T_EBEK_MIKAD(TBL_T_EBEK_MIKAD instance);
    partial void DeleteTBL_T_EBEK_MIKAD(TBL_T_EBEK_MIKAD instance);
    partial void InsertTBL_T_EBEK_COI(TBL_T_EBEK_COI instance);
    partial void UpdateTBL_T_EBEK_COI(TBL_T_EBEK_COI instance);
    partial void DeleteTBL_T_EBEK_COI(TBL_T_EBEK_COI instance);
    partial void InsertTBL_T_PI(TBL_T_PI instance);
    partial void UpdateTBL_T_PI(TBL_T_PI instance);
    partial void DeleteTBL_T_PI(TBL_T_PI instance);
    partial void InsertTBL_T_EBEK(TBL_T_EBEK instance);
    partial void UpdateTBL_T_EBEK(TBL_T_EBEK instance);
    partial void DeleteTBL_T_EBEK(TBL_T_EBEK instance);
    partial void InsertTBL_T_GRATIFIKASI(TBL_T_GRATIFIKASI instance);
    partial void UpdateTBL_T_GRATIFIKASI(TBL_T_GRATIFIKASI instance);
    partial void DeleteTBL_T_GRATIFIKASI(TBL_T_GRATIFIKASI instance);
    #endregion
		
		public DBPakta_IntegritasDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DB_IA_PAKTA_INTEGRITAS_KPTConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBPakta_IntegritasDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBPakta_IntegritasDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBPakta_IntegritasDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBPakta_IntegritasDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TBL_M_ROLE> TBL_M_ROLEs
		{
			get
			{
				return this.GetTable<TBL_M_ROLE>();
			}
		}
		
		public System.Data.Linq.Table<TBL_R_USER> TBL_R_USERs
		{
			get
			{
				return this.GetTable<TBL_R_USER>();
			}
		}
		
		public System.Data.Linq.Table<TBL_T_EBEK_FAMILY> TBL_T_EBEK_FAMILies
		{
			get
			{
				return this.GetTable<TBL_T_EBEK_FAMILY>();
			}
		}
		
		public System.Data.Linq.Table<TBL_T_EBEK_MIKAD> TBL_T_EBEK_MIKADs
		{
			get
			{
				return this.GetTable<TBL_T_EBEK_MIKAD>();
			}
		}
		
		public System.Data.Linq.Table<TBL_T_EBEK_COI> TBL_T_EBEK_COIs
		{
			get
			{
				return this.GetTable<TBL_T_EBEK_COI>();
			}
		}
		
		public System.Data.Linq.Table<TBL_T_PI> TBL_T_PIs
		{
			get
			{
				return this.GetTable<TBL_T_PI>();
			}
		}
		
		public System.Data.Linq.Table<TBL_T_EBEK> TBL_T_EBEKs
		{
			get
			{
				return this.GetTable<TBL_T_EBEK>();
			}
		}
		
		public System.Data.Linq.Table<VW_ALL_USER> VW_ALL_USERs
		{
			get
			{
				return this.GetTable<VW_ALL_USER>();
			}
		}
		
		public System.Data.Linq.Table<VW_EBEK_REPORT> VW_EBEK_REPORTs
		{
			get
			{
				return this.GetTable<VW_EBEK_REPORT>();
			}
		}
		
		public System.Data.Linq.Table<VW_PI_REPORT> VW_PI_REPORTs
		{
			get
			{
				return this.GetTable<VW_PI_REPORT>();
			}
		}
		
		public System.Data.Linq.Table<VW_DEPT_ALL> VW_DEPT_ALLs
		{
			get
			{
				return this.GetTable<VW_DEPT_ALL>();
			}
		}
		
		public System.Data.Linq.Table<VW_DISTRICT_ALL> VW_DISTRICT_ALLs
		{
			get
			{
				return this.GetTable<VW_DISTRICT_ALL>();
			}
		}
		
		public System.Data.Linq.Table<TBL_T_GRATIFIKASI> TBL_T_GRATIFIKASIs
		{
			get
			{
				return this.GetTable<TBL_T_GRATIFIKASI>();
			}
		}
		
		public System.Data.Linq.Table<VW_GRATIFIKASI_REPORT_DEPTHEAD> VW_GRATIFIKASI_REPORT_DEPTHEADs
		{
			get
			{
				return this.GetTable<VW_GRATIFIKASI_REPORT_DEPTHEAD>();
			}
		}
		
		public System.Data.Linq.Table<VW_GRATIFIKASI_REPORT_PM> VW_GRATIFIKASI_REPORT_PMs
		{
			get
			{
				return this.GetTable<VW_GRATIFIKASI_REPORT_PM>();
			}
		}
		
		public System.Data.Linq.Table<VW_GRATIFIKASI_REPORT_BOD> VW_GRATIFIKASI_REPORT_BODs
		{
			get
			{
				return this.GetTable<VW_GRATIFIKASI_REPORT_BOD>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cusp_insertNotifProjectManager")]
		public ISingleResult<cusp_insertNotifProjectManagerResult> cusp_insertNotifProjectManager([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((ISingleResult<cusp_insertNotifProjectManagerResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cusp_insertNotifDeptHead")]
		public ISingleResult<cusp_insertNotifDeptHeadResult> cusp_insertNotifDeptHead([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((ISingleResult<cusp_insertNotifDeptHeadResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cusp_insertNotifBOD")]
		public ISingleResult<cusp_insertNotifBODResult> cusp_insertNotifBOD([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((ISingleResult<cusp_insertNotifBODResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_M_ROLE")]
	public partial class TBL_M_ROLE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ID;
		
		private string _ROLE;
		
		private System.Nullable<bool> _STATUS;
		
		private System.Nullable<System.Guid> _CREATED_BY;
		
		private System.Nullable<System.DateTime> _CREATED_DATE;
		
		private System.Nullable<System.Guid> _UPDATED_BY;
		
		private System.Nullable<System.DateTime> _UPDATED_DATE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(System.Guid value);
    partial void OnIDChanged();
    partial void OnROLEChanging(string value);
    partial void OnROLEChanged();
    partial void OnSTATUSChanging(System.Nullable<bool> value);
    partial void OnSTATUSChanged();
    partial void OnCREATED_BYChanging(System.Nullable<System.Guid> value);
    partial void OnCREATED_BYChanged();
    partial void OnCREATED_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnCREATED_DATEChanged();
    partial void OnUPDATED_BYChanging(System.Nullable<System.Guid> value);
    partial void OnUPDATED_BYChanged();
    partial void OnUPDATED_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnUPDATED_DATEChanged();
    #endregion
		
		public TBL_M_ROLE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROLE", DbType="NVarChar(50)")]
		public string ROLE
		{
			get
			{
				return this._ROLE;
			}
			set
			{
				if ((this._ROLE != value))
				{
					this.OnROLEChanging(value);
					this.SendPropertyChanging();
					this._ROLE = value;
					this.SendPropertyChanged("ROLE");
					this.OnROLEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="Bit")]
		public System.Nullable<bool> STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this.OnSTATUSChanging(value);
					this.SendPropertyChanging();
					this._STATUS = value;
					this.SendPropertyChanged("STATUS");
					this.OnSTATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATED_BY", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> CREATED_BY
		{
			get
			{
				return this._CREATED_BY;
			}
			set
			{
				if ((this._CREATED_BY != value))
				{
					this.OnCREATED_BYChanging(value);
					this.SendPropertyChanging();
					this._CREATED_BY = value;
					this.SendPropertyChanged("CREATED_BY");
					this.OnCREATED_BYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATED_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATED_DATE
		{
			get
			{
				return this._CREATED_DATE;
			}
			set
			{
				if ((this._CREATED_DATE != value))
				{
					this.OnCREATED_DATEChanging(value);
					this.SendPropertyChanging();
					this._CREATED_DATE = value;
					this.SendPropertyChanged("CREATED_DATE");
					this.OnCREATED_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATED_BY", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> UPDATED_BY
		{
			get
			{
				return this._UPDATED_BY;
			}
			set
			{
				if ((this._UPDATED_BY != value))
				{
					this.OnUPDATED_BYChanging(value);
					this.SendPropertyChanging();
					this._UPDATED_BY = value;
					this.SendPropertyChanged("UPDATED_BY");
					this.OnUPDATED_BYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATED_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> UPDATED_DATE
		{
			get
			{
				return this._UPDATED_DATE;
			}
			set
			{
				if ((this._UPDATED_DATE != value))
				{
					this.OnUPDATED_DATEChanging(value);
					this.SendPropertyChanging();
					this._UPDATED_DATE = value;
					this.SendPropertyChanged("UPDATED_DATE");
					this.OnUPDATED_DATEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_R_USER")]
	public partial class TBL_R_USER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ID;
		
		private string _NRP;
		
		private System.Nullable<System.Guid> _ROLE;
		
		private System.Nullable<bool> _STATUS;
		
		private System.Nullable<System.Guid> _CREATED_BY;
		
		private System.Nullable<System.DateTime> _CREATED_DATE;
		
		private System.Nullable<System.Guid> _UPDATED_BY;
		
		private System.Nullable<System.DateTime> _UPDATED_DATE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(System.Guid value);
    partial void OnIDChanged();
    partial void OnNRPChanging(string value);
    partial void OnNRPChanged();
    partial void OnROLEChanging(System.Nullable<System.Guid> value);
    partial void OnROLEChanged();
    partial void OnSTATUSChanging(System.Nullable<bool> value);
    partial void OnSTATUSChanged();
    partial void OnCREATED_BYChanging(System.Nullable<System.Guid> value);
    partial void OnCREATED_BYChanged();
    partial void OnCREATED_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnCREATED_DATEChanged();
    partial void OnUPDATED_BYChanging(System.Nullable<System.Guid> value);
    partial void OnUPDATED_BYChanged();
    partial void OnUPDATED_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnUPDATED_DATEChanged();
    #endregion
		
		public TBL_R_USER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NRP", DbType="NVarChar(50)")]
		public string NRP
		{
			get
			{
				return this._NRP;
			}
			set
			{
				if ((this._NRP != value))
				{
					this.OnNRPChanging(value);
					this.SendPropertyChanging();
					this._NRP = value;
					this.SendPropertyChanged("NRP");
					this.OnNRPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROLE", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> ROLE
		{
			get
			{
				return this._ROLE;
			}
			set
			{
				if ((this._ROLE != value))
				{
					this.OnROLEChanging(value);
					this.SendPropertyChanging();
					this._ROLE = value;
					this.SendPropertyChanged("ROLE");
					this.OnROLEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="Bit")]
		public System.Nullable<bool> STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this.OnSTATUSChanging(value);
					this.SendPropertyChanging();
					this._STATUS = value;
					this.SendPropertyChanged("STATUS");
					this.OnSTATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATED_BY", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> CREATED_BY
		{
			get
			{
				return this._CREATED_BY;
			}
			set
			{
				if ((this._CREATED_BY != value))
				{
					this.OnCREATED_BYChanging(value);
					this.SendPropertyChanging();
					this._CREATED_BY = value;
					this.SendPropertyChanged("CREATED_BY");
					this.OnCREATED_BYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATED_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATED_DATE
		{
			get
			{
				return this._CREATED_DATE;
			}
			set
			{
				if ((this._CREATED_DATE != value))
				{
					this.OnCREATED_DATEChanging(value);
					this.SendPropertyChanging();
					this._CREATED_DATE = value;
					this.SendPropertyChanged("CREATED_DATE");
					this.OnCREATED_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATED_BY", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> UPDATED_BY
		{
			get
			{
				return this._UPDATED_BY;
			}
			set
			{
				if ((this._UPDATED_BY != value))
				{
					this.OnUPDATED_BYChanging(value);
					this.SendPropertyChanging();
					this._UPDATED_BY = value;
					this.SendPropertyChanged("UPDATED_BY");
					this.OnUPDATED_BYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATED_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> UPDATED_DATE
		{
			get
			{
				return this._UPDATED_DATE;
			}
			set
			{
				if ((this._UPDATED_DATE != value))
				{
					this.OnUPDATED_DATEChanging(value);
					this.SendPropertyChanging();
					this._UPDATED_DATE = value;
					this.SendPropertyChanged("UPDATED_DATE");
					this.OnUPDATED_DATEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_T_EBEK_FAMILY")]
	public partial class TBL_T_EBEK_FAMILY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ID;
		
		private System.Guid _EBEK_ID;
		
		private string _NAME;
		
		private string _POSITION;
		
		private string _DEPT;
		
		private string _RELATION;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(System.Guid value);
    partial void OnIDChanged();
    partial void OnEBEK_IDChanging(System.Guid value);
    partial void OnEBEK_IDChanged();
    partial void OnNAMEChanging(string value);
    partial void OnNAMEChanged();
    partial void OnPOSITIONChanging(string value);
    partial void OnPOSITIONChanged();
    partial void OnDEPTChanging(string value);
    partial void OnDEPTChanged();
    partial void OnRELATIONChanging(string value);
    partial void OnRELATIONChanged();
    #endregion
		
		public TBL_T_EBEK_FAMILY()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true, IsDbGenerated=true)]
		public System.Guid ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EBEK_ID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid EBEK_ID
		{
			get
			{
				return this._EBEK_ID;
			}
			set
			{
				if ((this._EBEK_ID != value))
				{
					this.OnEBEK_IDChanging(value);
					this.SendPropertyChanging();
					this._EBEK_ID = value;
					this.SendPropertyChanged("EBEK_ID");
					this.OnEBEK_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(50)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this.OnNAMEChanging(value);
					this.SendPropertyChanging();
					this._NAME = value;
					this.SendPropertyChanged("NAME");
					this.OnNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSITION", DbType="NVarChar(50)")]
		public string POSITION
		{
			get
			{
				return this._POSITION;
			}
			set
			{
				if ((this._POSITION != value))
				{
					this.OnPOSITIONChanging(value);
					this.SendPropertyChanging();
					this._POSITION = value;
					this.SendPropertyChanged("POSITION");
					this.OnPOSITIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT", DbType="NVarChar(50)")]
		public string DEPT
		{
			get
			{
				return this._DEPT;
			}
			set
			{
				if ((this._DEPT != value))
				{
					this.OnDEPTChanging(value);
					this.SendPropertyChanging();
					this._DEPT = value;
					this.SendPropertyChanged("DEPT");
					this.OnDEPTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RELATION", DbType="NVarChar(50)")]
		public string RELATION
		{
			get
			{
				return this._RELATION;
			}
			set
			{
				if ((this._RELATION != value))
				{
					this.OnRELATIONChanging(value);
					this.SendPropertyChanging();
					this._RELATION = value;
					this.SendPropertyChanged("RELATION");
					this.OnRELATIONChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_T_EBEK_MIKAD")]
	public partial class TBL_T_EBEK_MIKAD : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ID;
		
		private System.Guid _EBEK_ID;
		
		private string _NAME;
		
		private string _POSITION;
		
		private string _DEPT;
		
		private string _RELATION;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(System.Guid value);
    partial void OnIDChanged();
    partial void OnEBEK_IDChanging(System.Guid value);
    partial void OnEBEK_IDChanged();
    partial void OnNAMEChanging(string value);
    partial void OnNAMEChanged();
    partial void OnPOSITIONChanging(string value);
    partial void OnPOSITIONChanged();
    partial void OnDEPTChanging(string value);
    partial void OnDEPTChanged();
    partial void OnRELATIONChanging(string value);
    partial void OnRELATIONChanged();
    #endregion
		
		public TBL_T_EBEK_MIKAD()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true, IsDbGenerated=true)]
		public System.Guid ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EBEK_ID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid EBEK_ID
		{
			get
			{
				return this._EBEK_ID;
			}
			set
			{
				if ((this._EBEK_ID != value))
				{
					this.OnEBEK_IDChanging(value);
					this.SendPropertyChanging();
					this._EBEK_ID = value;
					this.SendPropertyChanged("EBEK_ID");
					this.OnEBEK_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(50)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this.OnNAMEChanging(value);
					this.SendPropertyChanging();
					this._NAME = value;
					this.SendPropertyChanged("NAME");
					this.OnNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSITION", DbType="NVarChar(50)")]
		public string POSITION
		{
			get
			{
				return this._POSITION;
			}
			set
			{
				if ((this._POSITION != value))
				{
					this.OnPOSITIONChanging(value);
					this.SendPropertyChanging();
					this._POSITION = value;
					this.SendPropertyChanged("POSITION");
					this.OnPOSITIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT", DbType="NVarChar(50)")]
		public string DEPT
		{
			get
			{
				return this._DEPT;
			}
			set
			{
				if ((this._DEPT != value))
				{
					this.OnDEPTChanging(value);
					this.SendPropertyChanging();
					this._DEPT = value;
					this.SendPropertyChanged("DEPT");
					this.OnDEPTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RELATION", DbType="NVarChar(50)")]
		public string RELATION
		{
			get
			{
				return this._RELATION;
			}
			set
			{
				if ((this._RELATION != value))
				{
					this.OnRELATIONChanging(value);
					this.SendPropertyChanging();
					this._RELATION = value;
					this.SendPropertyChanged("RELATION");
					this.OnRELATIONChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_T_EBEK_COI")]
	public partial class TBL_T_EBEK_COI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ID;
		
		private System.Guid _EBEK_ID;
		
		private string _CATEGORY;
		
		private string _COMPANY;
		
		private string _POSITION;
		
		private string _INFORMATION;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(System.Guid value);
    partial void OnIDChanged();
    partial void OnEBEK_IDChanging(System.Guid value);
    partial void OnEBEK_IDChanged();
    partial void OnCATEGORYChanging(string value);
    partial void OnCATEGORYChanged();
    partial void OnCOMPANYChanging(string value);
    partial void OnCOMPANYChanged();
    partial void OnPOSITIONChanging(string value);
    partial void OnPOSITIONChanged();
    partial void OnINFORMATIONChanging(string value);
    partial void OnINFORMATIONChanged();
    #endregion
		
		public TBL_T_EBEK_COI()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true, IsDbGenerated=true)]
		public System.Guid ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EBEK_ID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid EBEK_ID
		{
			get
			{
				return this._EBEK_ID;
			}
			set
			{
				if ((this._EBEK_ID != value))
				{
					this.OnEBEK_IDChanging(value);
					this.SendPropertyChanging();
					this._EBEK_ID = value;
					this.SendPropertyChanged("EBEK_ID");
					this.OnEBEK_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CATEGORY", DbType="NVarChar(50)")]
		public string CATEGORY
		{
			get
			{
				return this._CATEGORY;
			}
			set
			{
				if ((this._CATEGORY != value))
				{
					this.OnCATEGORYChanging(value);
					this.SendPropertyChanging();
					this._CATEGORY = value;
					this.SendPropertyChanged("CATEGORY");
					this.OnCATEGORYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMPANY", DbType="NVarChar(50)")]
		public string COMPANY
		{
			get
			{
				return this._COMPANY;
			}
			set
			{
				if ((this._COMPANY != value))
				{
					this.OnCOMPANYChanging(value);
					this.SendPropertyChanging();
					this._COMPANY = value;
					this.SendPropertyChanged("COMPANY");
					this.OnCOMPANYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSITION", DbType="NVarChar(50)")]
		public string POSITION
		{
			get
			{
				return this._POSITION;
			}
			set
			{
				if ((this._POSITION != value))
				{
					this.OnPOSITIONChanging(value);
					this.SendPropertyChanging();
					this._POSITION = value;
					this.SendPropertyChanged("POSITION");
					this.OnPOSITIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INFORMATION", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string INFORMATION
		{
			get
			{
				return this._INFORMATION;
			}
			set
			{
				if ((this._INFORMATION != value))
				{
					this.OnINFORMATIONChanging(value);
					this.SendPropertyChanging();
					this._INFORMATION = value;
					this.SendPropertyChanged("INFORMATION");
					this.OnINFORMATIONChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_T_PI")]
	public partial class TBL_T_PI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ID;
		
		private string _PI_NO;
		
		private string _NRP;
		
		private System.Nullable<bool> _SUBMIT;
		
		private string _SIGN_LOCATION;
		
		private System.Nullable<System.DateTime> _SUBMITDATE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(System.Guid value);
    partial void OnIDChanged();
    partial void OnPI_NOChanging(string value);
    partial void OnPI_NOChanged();
    partial void OnNRPChanging(string value);
    partial void OnNRPChanged();
    partial void OnSUBMITChanging(System.Nullable<bool> value);
    partial void OnSUBMITChanged();
    partial void OnSIGN_LOCATIONChanging(string value);
    partial void OnSIGN_LOCATIONChanged();
    partial void OnSUBMITDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnSUBMITDATEChanged();
    #endregion
		
		public TBL_T_PI()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true, IsDbGenerated=true)]
		public System.Guid ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PI_NO", DbType="NVarChar(50)")]
		public string PI_NO
		{
			get
			{
				return this._PI_NO;
			}
			set
			{
				if ((this._PI_NO != value))
				{
					this.OnPI_NOChanging(value);
					this.SendPropertyChanging();
					this._PI_NO = value;
					this.SendPropertyChanged("PI_NO");
					this.OnPI_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NRP", DbType="NVarChar(50)")]
		public string NRP
		{
			get
			{
				return this._NRP;
			}
			set
			{
				if ((this._NRP != value))
				{
					this.OnNRPChanging(value);
					this.SendPropertyChanging();
					this._NRP = value;
					this.SendPropertyChanged("NRP");
					this.OnNRPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUBMIT", DbType="Bit")]
		public System.Nullable<bool> SUBMIT
		{
			get
			{
				return this._SUBMIT;
			}
			set
			{
				if ((this._SUBMIT != value))
				{
					this.OnSUBMITChanging(value);
					this.SendPropertyChanging();
					this._SUBMIT = value;
					this.SendPropertyChanged("SUBMIT");
					this.OnSUBMITChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SIGN_LOCATION", DbType="NVarChar(100)")]
		public string SIGN_LOCATION
		{
			get
			{
				return this._SIGN_LOCATION;
			}
			set
			{
				if ((this._SIGN_LOCATION != value))
				{
					this.OnSIGN_LOCATIONChanging(value);
					this.SendPropertyChanging();
					this._SIGN_LOCATION = value;
					this.SendPropertyChanged("SIGN_LOCATION");
					this.OnSIGN_LOCATIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUBMITDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> SUBMITDATE
		{
			get
			{
				return this._SUBMITDATE;
			}
			set
			{
				if ((this._SUBMITDATE != value))
				{
					this.OnSUBMITDATEChanging(value);
					this.SendPropertyChanging();
					this._SUBMITDATE = value;
					this.SendPropertyChanged("SUBMITDATE");
					this.OnSUBMITDATEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_T_EBEK")]
	public partial class TBL_T_EBEK : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ID;
		
		private string _EBEK_NO;
		
		private string _NRP;
		
		private System.Nullable<bool> _SUBMIT;
		
		private string _SIGN_LOCATION;
		
		private System.Nullable<System.DateTime> _SUBMITDATE;
		
		private System.Nullable<bool> _ISHADFAMILY;
		
		private System.Nullable<bool> _ISHADMIKAD;
		
		private System.Nullable<bool> _ISHADCOI;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(System.Guid value);
    partial void OnIDChanged();
    partial void OnEBEK_NOChanging(string value);
    partial void OnEBEK_NOChanged();
    partial void OnNRPChanging(string value);
    partial void OnNRPChanged();
    partial void OnSUBMITChanging(System.Nullable<bool> value);
    partial void OnSUBMITChanged();
    partial void OnSIGN_LOCATIONChanging(string value);
    partial void OnSIGN_LOCATIONChanged();
    partial void OnSUBMITDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnSUBMITDATEChanged();
    partial void OnISHADFAMILYChanging(System.Nullable<bool> value);
    partial void OnISHADFAMILYChanged();
    partial void OnISHADMIKADChanging(System.Nullable<bool> value);
    partial void OnISHADMIKADChanged();
    partial void OnISHADCOIChanging(System.Nullable<bool> value);
    partial void OnISHADCOIChanged();
    #endregion
		
		public TBL_T_EBEK()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true, IsDbGenerated=true)]
		public System.Guid ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EBEK_NO", DbType="NVarChar(50)")]
		public string EBEK_NO
		{
			get
			{
				return this._EBEK_NO;
			}
			set
			{
				if ((this._EBEK_NO != value))
				{
					this.OnEBEK_NOChanging(value);
					this.SendPropertyChanging();
					this._EBEK_NO = value;
					this.SendPropertyChanged("EBEK_NO");
					this.OnEBEK_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NRP", DbType="NVarChar(50)")]
		public string NRP
		{
			get
			{
				return this._NRP;
			}
			set
			{
				if ((this._NRP != value))
				{
					this.OnNRPChanging(value);
					this.SendPropertyChanging();
					this._NRP = value;
					this.SendPropertyChanged("NRP");
					this.OnNRPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUBMIT", DbType="Bit")]
		public System.Nullable<bool> SUBMIT
		{
			get
			{
				return this._SUBMIT;
			}
			set
			{
				if ((this._SUBMIT != value))
				{
					this.OnSUBMITChanging(value);
					this.SendPropertyChanging();
					this._SUBMIT = value;
					this.SendPropertyChanged("SUBMIT");
					this.OnSUBMITChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SIGN_LOCATION", DbType="NVarChar(100)")]
		public string SIGN_LOCATION
		{
			get
			{
				return this._SIGN_LOCATION;
			}
			set
			{
				if ((this._SIGN_LOCATION != value))
				{
					this.OnSIGN_LOCATIONChanging(value);
					this.SendPropertyChanging();
					this._SIGN_LOCATION = value;
					this.SendPropertyChanged("SIGN_LOCATION");
					this.OnSIGN_LOCATIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUBMITDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> SUBMITDATE
		{
			get
			{
				return this._SUBMITDATE;
			}
			set
			{
				if ((this._SUBMITDATE != value))
				{
					this.OnSUBMITDATEChanging(value);
					this.SendPropertyChanging();
					this._SUBMITDATE = value;
					this.SendPropertyChanged("SUBMITDATE");
					this.OnSUBMITDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISHADFAMILY", DbType="Bit")]
		public System.Nullable<bool> ISHADFAMILY
		{
			get
			{
				return this._ISHADFAMILY;
			}
			set
			{
				if ((this._ISHADFAMILY != value))
				{
					this.OnISHADFAMILYChanging(value);
					this.SendPropertyChanging();
					this._ISHADFAMILY = value;
					this.SendPropertyChanged("ISHADFAMILY");
					this.OnISHADFAMILYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISHADMIKAD", DbType="Bit")]
		public System.Nullable<bool> ISHADMIKAD
		{
			get
			{
				return this._ISHADMIKAD;
			}
			set
			{
				if ((this._ISHADMIKAD != value))
				{
					this.OnISHADMIKADChanging(value);
					this.SendPropertyChanging();
					this._ISHADMIKAD = value;
					this.SendPropertyChanged("ISHADMIKAD");
					this.OnISHADMIKADChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISHADCOI", DbType="Bit")]
		public System.Nullable<bool> ISHADCOI
		{
			get
			{
				return this._ISHADCOI;
			}
			set
			{
				if ((this._ISHADCOI != value))
				{
					this.OnISHADCOIChanging(value);
					this.SendPropertyChanging();
					this._ISHADCOI = value;
					this.SendPropertyChanged("ISHADCOI");
					this.OnISHADCOIChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_ALL_USER")]
	public partial class VW_ALL_USER
	{
		
		private string _EMPLOYEE_ID;
		
		private string _NAME;
		
		private string _POSITION_ID;
		
		private string _POS_TITLE;
		
		private string _DSTRCT_CODE;
		
		private string _DEPT_CODE;
		
		private string _DEPT_DESC;
		
		private string _alamat;
		
		private string _HIRE_DATE;
		
		private string _GENDER_CODE;
		
		private string _No_telp;
		
		private string _ROLE;
		
		private System.Nullable<bool> _PI_SUBMIT;
		
		private System.Nullable<bool> _EBEK_SUBMIT;
		
		private string _SECTION_HEAD;
		
		public VW_ALL_USER()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMPLOYEE_ID", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string EMPLOYEE_ID
		{
			get
			{
				return this._EMPLOYEE_ID;
			}
			set
			{
				if ((this._EMPLOYEE_ID != value))
				{
					this._EMPLOYEE_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="VarChar(100)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSITION_ID", DbType="VarChar(100)")]
		public string POSITION_ID
		{
			get
			{
				return this._POSITION_ID;
			}
			set
			{
				if ((this._POSITION_ID != value))
				{
					this._POSITION_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POS_TITLE", DbType="VarChar(100)")]
		public string POS_TITLE
		{
			get
			{
				return this._POS_TITLE;
			}
			set
			{
				if ((this._POS_TITLE != value))
				{
					this._POS_TITLE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSTRCT_CODE", DbType="VarChar(100)")]
		public string DSTRCT_CODE
		{
			get
			{
				return this._DSTRCT_CODE;
			}
			set
			{
				if ((this._DSTRCT_CODE != value))
				{
					this._DSTRCT_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_CODE", DbType="VarChar(100)")]
		public string DEPT_CODE
		{
			get
			{
				return this._DEPT_CODE;
			}
			set
			{
				if ((this._DEPT_CODE != value))
				{
					this._DEPT_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_DESC", DbType="VarChar(100)")]
		public string DEPT_DESC
		{
			get
			{
				return this._DEPT_DESC;
			}
			set
			{
				if ((this._DEPT_DESC != value))
				{
					this._DEPT_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alamat", DbType="VarChar(303)")]
		public string alamat
		{
			get
			{
				return this._alamat;
			}
			set
			{
				if ((this._alamat != value))
				{
					this._alamat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HIRE_DATE", DbType="VarChar(100)")]
		public string HIRE_DATE
		{
			get
			{
				return this._HIRE_DATE;
			}
			set
			{
				if ((this._HIRE_DATE != value))
				{
					this._HIRE_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GENDER_CODE", DbType="VarChar(100)")]
		public string GENDER_CODE
		{
			get
			{
				return this._GENDER_CODE;
			}
			set
			{
				if ((this._GENDER_CODE != value))
				{
					this._GENDER_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_No_telp", DbType="VarChar(100)")]
		public string No_telp
		{
			get
			{
				return this._No_telp;
			}
			set
			{
				if ((this._No_telp != value))
				{
					this._No_telp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROLE", DbType="NVarChar(50)")]
		public string ROLE
		{
			get
			{
				return this._ROLE;
			}
			set
			{
				if ((this._ROLE != value))
				{
					this._ROLE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PI_SUBMIT", DbType="Bit")]
		public System.Nullable<bool> PI_SUBMIT
		{
			get
			{
				return this._PI_SUBMIT;
			}
			set
			{
				if ((this._PI_SUBMIT != value))
				{
					this._PI_SUBMIT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EBEK_SUBMIT", DbType="Bit")]
		public System.Nullable<bool> EBEK_SUBMIT
		{
			get
			{
				return this._EBEK_SUBMIT;
			}
			set
			{
				if ((this._EBEK_SUBMIT != value))
				{
					this._EBEK_SUBMIT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SECTION_HEAD", DbType="NVarChar(50)")]
		public string SECTION_HEAD
		{
			get
			{
				return this._SECTION_HEAD;
			}
			set
			{
				if ((this._SECTION_HEAD != value))
				{
					this._SECTION_HEAD = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_EBEK_REPORT")]
	public partial class VW_EBEK_REPORT
	{
		
		private string _NRP;
		
		private System.Nullable<bool> _SUBMIT;
		
		private string _SIGN_LOCATION;
		
		private System.Nullable<System.DateTime> _SUBMITDATE;
		
		private System.Nullable<bool> _ISHADFAMILY;
		
		private System.Nullable<bool> _ISHADMIKAD;
		
		private System.Nullable<bool> _ISHADCOI;
		
		private string _NAME;
		
		private string _DEPT;
		
		private string _SITE;
		
		public VW_EBEK_REPORT()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NRP", DbType="NVarChar(50)")]
		public string NRP
		{
			get
			{
				return this._NRP;
			}
			set
			{
				if ((this._NRP != value))
				{
					this._NRP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUBMIT", DbType="Bit")]
		public System.Nullable<bool> SUBMIT
		{
			get
			{
				return this._SUBMIT;
			}
			set
			{
				if ((this._SUBMIT != value))
				{
					this._SUBMIT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SIGN_LOCATION", DbType="NVarChar(100)")]
		public string SIGN_LOCATION
		{
			get
			{
				return this._SIGN_LOCATION;
			}
			set
			{
				if ((this._SIGN_LOCATION != value))
				{
					this._SIGN_LOCATION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUBMITDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> SUBMITDATE
		{
			get
			{
				return this._SUBMITDATE;
			}
			set
			{
				if ((this._SUBMITDATE != value))
				{
					this._SUBMITDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISHADFAMILY", DbType="Bit")]
		public System.Nullable<bool> ISHADFAMILY
		{
			get
			{
				return this._ISHADFAMILY;
			}
			set
			{
				if ((this._ISHADFAMILY != value))
				{
					this._ISHADFAMILY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISHADMIKAD", DbType="Bit")]
		public System.Nullable<bool> ISHADMIKAD
		{
			get
			{
				return this._ISHADMIKAD;
			}
			set
			{
				if ((this._ISHADMIKAD != value))
				{
					this._ISHADMIKAD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISHADCOI", DbType="Bit")]
		public System.Nullable<bool> ISHADCOI
		{
			get
			{
				return this._ISHADCOI;
			}
			set
			{
				if ((this._ISHADCOI != value))
				{
					this._ISHADCOI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="VarChar(43)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT", DbType="VarChar(50)")]
		public string DEPT
		{
			get
			{
				return this._DEPT;
			}
			set
			{
				if ((this._DEPT != value))
				{
					this._DEPT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SITE", DbType="VarChar(50)")]
		public string SITE
		{
			get
			{
				return this._SITE;
			}
			set
			{
				if ((this._SITE != value))
				{
					this._SITE = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_PI_REPORT")]
	public partial class VW_PI_REPORT
	{
		
		private string _NRP;
		
		private System.Nullable<bool> _SUBMIT;
		
		private string _SIGN_LOCATION;
		
		private System.Nullable<System.DateTime> _SUBMITDATE;
		
		private string _NAME;
		
		private string _DEPT;
		
		private string _SITE;
		
		public VW_PI_REPORT()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NRP", DbType="NVarChar(50)")]
		public string NRP
		{
			get
			{
				return this._NRP;
			}
			set
			{
				if ((this._NRP != value))
				{
					this._NRP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUBMIT", DbType="Bit")]
		public System.Nullable<bool> SUBMIT
		{
			get
			{
				return this._SUBMIT;
			}
			set
			{
				if ((this._SUBMIT != value))
				{
					this._SUBMIT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SIGN_LOCATION", DbType="NVarChar(100)")]
		public string SIGN_LOCATION
		{
			get
			{
				return this._SIGN_LOCATION;
			}
			set
			{
				if ((this._SIGN_LOCATION != value))
				{
					this._SIGN_LOCATION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUBMITDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> SUBMITDATE
		{
			get
			{
				return this._SUBMITDATE;
			}
			set
			{
				if ((this._SUBMITDATE != value))
				{
					this._SUBMITDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="VarChar(43)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT", DbType="VarChar(50)")]
		public string DEPT
		{
			get
			{
				return this._DEPT;
			}
			set
			{
				if ((this._DEPT != value))
				{
					this._DEPT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SITE", DbType="VarChar(50)")]
		public string SITE
		{
			get
			{
				return this._SITE;
			}
			set
			{
				if ((this._SITE != value))
				{
					this._SITE = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_DEPT_ALL")]
	public partial class VW_DEPT_ALL
	{
		
		private string _DEPT_CODE;
		
		private string _DEPT_DESC;
		
		private string _DEPT_NAME;
		
		public VW_DEPT_ALL()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_CODE", DbType="VarChar(100)")]
		public string DEPT_CODE
		{
			get
			{
				return this._DEPT_CODE;
			}
			set
			{
				if ((this._DEPT_CODE != value))
				{
					this._DEPT_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_DESC", DbType="VarChar(100)")]
		public string DEPT_DESC
		{
			get
			{
				return this._DEPT_DESC;
			}
			set
			{
				if ((this._DEPT_DESC != value))
				{
					this._DEPT_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_NAME", DbType="VarChar(100)")]
		public string DEPT_NAME
		{
			get
			{
				return this._DEPT_NAME;
			}
			set
			{
				if ((this._DEPT_NAME != value))
				{
					this._DEPT_NAME = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_DISTRICT_ALL")]
	public partial class VW_DISTRICT_ALL
	{
		
		private string _DSTRCT_CODE;
		
		private string _DSTRCT_NAME;
		
		private string _DSTRCT_STATUS;
		
		public VW_DISTRICT_ALL()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSTRCT_CODE", DbType="VarChar(100)")]
		public string DSTRCT_CODE
		{
			get
			{
				return this._DSTRCT_CODE;
			}
			set
			{
				if ((this._DSTRCT_CODE != value))
				{
					this._DSTRCT_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSTRCT_NAME", DbType="VarChar(100)")]
		public string DSTRCT_NAME
		{
			get
			{
				return this._DSTRCT_NAME;
			}
			set
			{
				if ((this._DSTRCT_NAME != value))
				{
					this._DSTRCT_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSTRCT_STATUS", DbType="VarChar(100)")]
		public string DSTRCT_STATUS
		{
			get
			{
				return this._DSTRCT_STATUS;
			}
			set
			{
				if ((this._DSTRCT_STATUS != value))
				{
					this._DSTRCT_STATUS = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_T_GRATIFIKASI")]
	public partial class TBL_T_GRATIFIKASI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _NRP;
		
		private System.Nullable<System.DateTime> _CREATED_DATE;
		
		private string _STATUS;
		
		private string _UPDATED_BY;
		
		private System.Nullable<System.DateTime> _UPDATED_DATE;
		
		private string _JENIS_PENERIMAAN;
		
		private string _ESTIMASI_HARGA;
		
		private string _TEMPAT_PENERIMAAN;
		
		private System.Nullable<System.DateTime> _TANGGAL_PENERIMAAN;
		
		private string _NAMA_PEMBERI;
		
		private string _PEKERJAAN_PEMBERI;
		
		private string _NAMA_PERUSAHAAN;
		
		private string _HUBUNGAN_PEMBERI;
		
		private string _ALASAN_PEMBERIAN;
		
		private string _BUKTI_GRATIFIKASI;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNRPChanging(string value);
    partial void OnNRPChanged();
    partial void OnCREATED_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnCREATED_DATEChanged();
    partial void OnSTATUSChanging(string value);
    partial void OnSTATUSChanged();
    partial void OnUPDATED_BYChanging(string value);
    partial void OnUPDATED_BYChanged();
    partial void OnUPDATED_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnUPDATED_DATEChanged();
    partial void OnJENIS_PENERIMAANChanging(string value);
    partial void OnJENIS_PENERIMAANChanged();
    partial void OnESTIMASI_HARGAChanging(string value);
    partial void OnESTIMASI_HARGAChanged();
    partial void OnTEMPAT_PENERIMAANChanging(string value);
    partial void OnTEMPAT_PENERIMAANChanged();
    partial void OnTANGGAL_PENERIMAANChanging(System.Nullable<System.DateTime> value);
    partial void OnTANGGAL_PENERIMAANChanged();
    partial void OnNAMA_PEMBERIChanging(string value);
    partial void OnNAMA_PEMBERIChanged();
    partial void OnPEKERJAAN_PEMBERIChanging(string value);
    partial void OnPEKERJAAN_PEMBERIChanged();
    partial void OnNAMA_PERUSAHAANChanging(string value);
    partial void OnNAMA_PERUSAHAANChanged();
    partial void OnHUBUNGAN_PEMBERIChanging(string value);
    partial void OnHUBUNGAN_PEMBERIChanged();
    partial void OnALASAN_PEMBERIANChanging(string value);
    partial void OnALASAN_PEMBERIANChanged();
    partial void OnBUKTI_GRATIFIKASIChanging(string value);
    partial void OnBUKTI_GRATIFIKASIChanged();
    #endregion
		
		public TBL_T_GRATIFIKASI()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NRP", DbType="VarChar(50)")]
		public string NRP
		{
			get
			{
				return this._NRP;
			}
			set
			{
				if ((this._NRP != value))
				{
					this.OnNRPChanging(value);
					this.SendPropertyChanging();
					this._NRP = value;
					this.SendPropertyChanged("NRP");
					this.OnNRPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATED_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATED_DATE
		{
			get
			{
				return this._CREATED_DATE;
			}
			set
			{
				if ((this._CREATED_DATE != value))
				{
					this.OnCREATED_DATEChanging(value);
					this.SendPropertyChanging();
					this._CREATED_DATE = value;
					this.SendPropertyChanged("CREATED_DATE");
					this.OnCREATED_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="VarChar(50)")]
		public string STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this.OnSTATUSChanging(value);
					this.SendPropertyChanging();
					this._STATUS = value;
					this.SendPropertyChanged("STATUS");
					this.OnSTATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATED_BY", DbType="VarChar(50)")]
		public string UPDATED_BY
		{
			get
			{
				return this._UPDATED_BY;
			}
			set
			{
				if ((this._UPDATED_BY != value))
				{
					this.OnUPDATED_BYChanging(value);
					this.SendPropertyChanging();
					this._UPDATED_BY = value;
					this.SendPropertyChanged("UPDATED_BY");
					this.OnUPDATED_BYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATED_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> UPDATED_DATE
		{
			get
			{
				return this._UPDATED_DATE;
			}
			set
			{
				if ((this._UPDATED_DATE != value))
				{
					this.OnUPDATED_DATEChanging(value);
					this.SendPropertyChanging();
					this._UPDATED_DATE = value;
					this.SendPropertyChanged("UPDATED_DATE");
					this.OnUPDATED_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JENIS_PENERIMAAN", DbType="VarChar(50)")]
		public string JENIS_PENERIMAAN
		{
			get
			{
				return this._JENIS_PENERIMAAN;
			}
			set
			{
				if ((this._JENIS_PENERIMAAN != value))
				{
					this.OnJENIS_PENERIMAANChanging(value);
					this.SendPropertyChanging();
					this._JENIS_PENERIMAAN = value;
					this.SendPropertyChanged("JENIS_PENERIMAAN");
					this.OnJENIS_PENERIMAANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTIMASI_HARGA", DbType="VarChar(50)")]
		public string ESTIMASI_HARGA
		{
			get
			{
				return this._ESTIMASI_HARGA;
			}
			set
			{
				if ((this._ESTIMASI_HARGA != value))
				{
					this.OnESTIMASI_HARGAChanging(value);
					this.SendPropertyChanging();
					this._ESTIMASI_HARGA = value;
					this.SendPropertyChanged("ESTIMASI_HARGA");
					this.OnESTIMASI_HARGAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEMPAT_PENERIMAAN", DbType="VarChar(50)")]
		public string TEMPAT_PENERIMAAN
		{
			get
			{
				return this._TEMPAT_PENERIMAAN;
			}
			set
			{
				if ((this._TEMPAT_PENERIMAAN != value))
				{
					this.OnTEMPAT_PENERIMAANChanging(value);
					this.SendPropertyChanging();
					this._TEMPAT_PENERIMAAN = value;
					this.SendPropertyChanged("TEMPAT_PENERIMAAN");
					this.OnTEMPAT_PENERIMAANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TANGGAL_PENERIMAAN", DbType="DateTime")]
		public System.Nullable<System.DateTime> TANGGAL_PENERIMAAN
		{
			get
			{
				return this._TANGGAL_PENERIMAAN;
			}
			set
			{
				if ((this._TANGGAL_PENERIMAAN != value))
				{
					this.OnTANGGAL_PENERIMAANChanging(value);
					this.SendPropertyChanging();
					this._TANGGAL_PENERIMAAN = value;
					this.SendPropertyChanged("TANGGAL_PENERIMAAN");
					this.OnTANGGAL_PENERIMAANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAMA_PEMBERI", DbType="VarChar(50)")]
		public string NAMA_PEMBERI
		{
			get
			{
				return this._NAMA_PEMBERI;
			}
			set
			{
				if ((this._NAMA_PEMBERI != value))
				{
					this.OnNAMA_PEMBERIChanging(value);
					this.SendPropertyChanging();
					this._NAMA_PEMBERI = value;
					this.SendPropertyChanged("NAMA_PEMBERI");
					this.OnNAMA_PEMBERIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PEKERJAAN_PEMBERI", DbType="VarChar(50)")]
		public string PEKERJAAN_PEMBERI
		{
			get
			{
				return this._PEKERJAAN_PEMBERI;
			}
			set
			{
				if ((this._PEKERJAAN_PEMBERI != value))
				{
					this.OnPEKERJAAN_PEMBERIChanging(value);
					this.SendPropertyChanging();
					this._PEKERJAAN_PEMBERI = value;
					this.SendPropertyChanged("PEKERJAAN_PEMBERI");
					this.OnPEKERJAAN_PEMBERIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAMA_PERUSAHAAN", DbType="VarChar(50)")]
		public string NAMA_PERUSAHAAN
		{
			get
			{
				return this._NAMA_PERUSAHAAN;
			}
			set
			{
				if ((this._NAMA_PERUSAHAAN != value))
				{
					this.OnNAMA_PERUSAHAANChanging(value);
					this.SendPropertyChanging();
					this._NAMA_PERUSAHAAN = value;
					this.SendPropertyChanged("NAMA_PERUSAHAAN");
					this.OnNAMA_PERUSAHAANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HUBUNGAN_PEMBERI", DbType="VarChar(50)")]
		public string HUBUNGAN_PEMBERI
		{
			get
			{
				return this._HUBUNGAN_PEMBERI;
			}
			set
			{
				if ((this._HUBUNGAN_PEMBERI != value))
				{
					this.OnHUBUNGAN_PEMBERIChanging(value);
					this.SendPropertyChanging();
					this._HUBUNGAN_PEMBERI = value;
					this.SendPropertyChanged("HUBUNGAN_PEMBERI");
					this.OnHUBUNGAN_PEMBERIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ALASAN_PEMBERIAN", DbType="VarChar(MAX)")]
		public string ALASAN_PEMBERIAN
		{
			get
			{
				return this._ALASAN_PEMBERIAN;
			}
			set
			{
				if ((this._ALASAN_PEMBERIAN != value))
				{
					this.OnALASAN_PEMBERIANChanging(value);
					this.SendPropertyChanging();
					this._ALASAN_PEMBERIAN = value;
					this.SendPropertyChanged("ALASAN_PEMBERIAN");
					this.OnALASAN_PEMBERIANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUKTI_GRATIFIKASI", DbType="VarChar(MAX)")]
		public string BUKTI_GRATIFIKASI
		{
			get
			{
				return this._BUKTI_GRATIFIKASI;
			}
			set
			{
				if ((this._BUKTI_GRATIFIKASI != value))
				{
					this.OnBUKTI_GRATIFIKASIChanging(value);
					this.SendPropertyChanging();
					this._BUKTI_GRATIFIKASI = value;
					this.SendPropertyChanged("BUKTI_GRATIFIKASI");
					this.OnBUKTI_GRATIFIKASIChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_GRATIFIKASI_REPORT_DEPTHEAD")]
	public partial class VW_GRATIFIKASI_REPORT_DEPTHEAD
	{
		
		private int _ID;
		
		private string _NRP;
		
		private string _POSITION_ID;
		
		private string _NAME;
		
		private string _EMAIL;
		
		private string _DEPT;
		
		private string _SITE;
		
		private System.Nullable<System.DateTime> _CREATED_DATE;
		
		private string _STATUS;
		
		private string _UPDATED_BY;
		
		private string _UPDATED_NAME;
		
		private System.Nullable<System.DateTime> _UPDATED_DATE;
		
		private string _JENIS_PENERIMAAN;
		
		private string _ESTIMASI_HARGA;
		
		private string _TEMPAT_PENERIMAAN;
		
		private System.Nullable<System.DateTime> _TANGGAL_PENERIMAAN;
		
		private string _NAMA_PEMBERI;
		
		private string _PEKERJAAN_PEMBERI;
		
		private string _NAMA_PERUSAHAAN;
		
		private string _HUBUNGAN_PEMBERI;
		
		private string _ALASAN_PEMBERIAN;
		
		private string _BUKTI_GRATIFIKASI;
		
		public VW_GRATIFIKASI_REPORT_DEPTHEAD()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NRP", DbType="VarChar(50)")]
		public string NRP
		{
			get
			{
				return this._NRP;
			}
			set
			{
				if ((this._NRP != value))
				{
					this._NRP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSITION_ID", DbType="Char(10)")]
		public string POSITION_ID
		{
			get
			{
				return this._POSITION_ID;
			}
			set
			{
				if ((this._POSITION_ID != value))
				{
					this._POSITION_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="VarChar(43)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="NVarChar(4000)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this._EMAIL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT", DbType="VarChar(50)")]
		public string DEPT
		{
			get
			{
				return this._DEPT;
			}
			set
			{
				if ((this._DEPT != value))
				{
					this._DEPT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SITE", DbType="VarChar(50)")]
		public string SITE
		{
			get
			{
				return this._SITE;
			}
			set
			{
				if ((this._SITE != value))
				{
					this._SITE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATED_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATED_DATE
		{
			get
			{
				return this._CREATED_DATE;
			}
			set
			{
				if ((this._CREATED_DATE != value))
				{
					this._CREATED_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="VarChar(50)")]
		public string STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this._STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATED_BY", DbType="VarChar(50)")]
		public string UPDATED_BY
		{
			get
			{
				return this._UPDATED_BY;
			}
			set
			{
				if ((this._UPDATED_BY != value))
				{
					this._UPDATED_BY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATED_NAME", DbType="VarChar(43)")]
		public string UPDATED_NAME
		{
			get
			{
				return this._UPDATED_NAME;
			}
			set
			{
				if ((this._UPDATED_NAME != value))
				{
					this._UPDATED_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATED_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> UPDATED_DATE
		{
			get
			{
				return this._UPDATED_DATE;
			}
			set
			{
				if ((this._UPDATED_DATE != value))
				{
					this._UPDATED_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JENIS_PENERIMAAN", DbType="VarChar(50)")]
		public string JENIS_PENERIMAAN
		{
			get
			{
				return this._JENIS_PENERIMAAN;
			}
			set
			{
				if ((this._JENIS_PENERIMAAN != value))
				{
					this._JENIS_PENERIMAAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTIMASI_HARGA", DbType="VarChar(50)")]
		public string ESTIMASI_HARGA
		{
			get
			{
				return this._ESTIMASI_HARGA;
			}
			set
			{
				if ((this._ESTIMASI_HARGA != value))
				{
					this._ESTIMASI_HARGA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEMPAT_PENERIMAAN", DbType="VarChar(50)")]
		public string TEMPAT_PENERIMAAN
		{
			get
			{
				return this._TEMPAT_PENERIMAAN;
			}
			set
			{
				if ((this._TEMPAT_PENERIMAAN != value))
				{
					this._TEMPAT_PENERIMAAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TANGGAL_PENERIMAAN", DbType="DateTime")]
		public System.Nullable<System.DateTime> TANGGAL_PENERIMAAN
		{
			get
			{
				return this._TANGGAL_PENERIMAAN;
			}
			set
			{
				if ((this._TANGGAL_PENERIMAAN != value))
				{
					this._TANGGAL_PENERIMAAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAMA_PEMBERI", DbType="VarChar(50)")]
		public string NAMA_PEMBERI
		{
			get
			{
				return this._NAMA_PEMBERI;
			}
			set
			{
				if ((this._NAMA_PEMBERI != value))
				{
					this._NAMA_PEMBERI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PEKERJAAN_PEMBERI", DbType="VarChar(50)")]
		public string PEKERJAAN_PEMBERI
		{
			get
			{
				return this._PEKERJAAN_PEMBERI;
			}
			set
			{
				if ((this._PEKERJAAN_PEMBERI != value))
				{
					this._PEKERJAAN_PEMBERI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAMA_PERUSAHAAN", DbType="VarChar(50)")]
		public string NAMA_PERUSAHAAN
		{
			get
			{
				return this._NAMA_PERUSAHAAN;
			}
			set
			{
				if ((this._NAMA_PERUSAHAAN != value))
				{
					this._NAMA_PERUSAHAAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HUBUNGAN_PEMBERI", DbType="VarChar(50)")]
		public string HUBUNGAN_PEMBERI
		{
			get
			{
				return this._HUBUNGAN_PEMBERI;
			}
			set
			{
				if ((this._HUBUNGAN_PEMBERI != value))
				{
					this._HUBUNGAN_PEMBERI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ALASAN_PEMBERIAN", DbType="VarChar(MAX)")]
		public string ALASAN_PEMBERIAN
		{
			get
			{
				return this._ALASAN_PEMBERIAN;
			}
			set
			{
				if ((this._ALASAN_PEMBERIAN != value))
				{
					this._ALASAN_PEMBERIAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUKTI_GRATIFIKASI", DbType="VarChar(MAX)")]
		public string BUKTI_GRATIFIKASI
		{
			get
			{
				return this._BUKTI_GRATIFIKASI;
			}
			set
			{
				if ((this._BUKTI_GRATIFIKASI != value))
				{
					this._BUKTI_GRATIFIKASI = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_GRATIFIKASI_REPORT_PM")]
	public partial class VW_GRATIFIKASI_REPORT_PM
	{
		
		private int _ID;
		
		private string _NRP;
		
		private string _NAME;
		
		private string _EMAIL;
		
		private string _DEPT;
		
		private string _SITE;
		
		private System.Nullable<System.DateTime> _CREATED_DATE;
		
		private string _STATUS;
		
		private string _UPDATED_BY;
		
		private string _UPDATED_NAME;
		
		private System.Nullable<System.DateTime> _UPDATED_DATE;
		
		private string _JENIS_PENERIMAAN;
		
		private string _ESTIMASI_HARGA;
		
		private string _TEMPAT_PENERIMAAN;
		
		private System.Nullable<System.DateTime> _TANGGAL_PENERIMAAN;
		
		private string _NAMA_PEMBERI;
		
		private string _PEKERJAAN_PEMBERI;
		
		private string _NAMA_PERUSAHAAN;
		
		private string _HUBUNGAN_PEMBERI;
		
		private string _ALASAN_PEMBERIAN;
		
		private string _BUKTI_GRATIFIKASI;
		
		public VW_GRATIFIKASI_REPORT_PM()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NRP", DbType="VarChar(50)")]
		public string NRP
		{
			get
			{
				return this._NRP;
			}
			set
			{
				if ((this._NRP != value))
				{
					this._NRP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="VarChar(43)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="NVarChar(4000)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this._EMAIL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT", DbType="VarChar(50)")]
		public string DEPT
		{
			get
			{
				return this._DEPT;
			}
			set
			{
				if ((this._DEPT != value))
				{
					this._DEPT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SITE", DbType="VarChar(50)")]
		public string SITE
		{
			get
			{
				return this._SITE;
			}
			set
			{
				if ((this._SITE != value))
				{
					this._SITE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATED_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATED_DATE
		{
			get
			{
				return this._CREATED_DATE;
			}
			set
			{
				if ((this._CREATED_DATE != value))
				{
					this._CREATED_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="VarChar(50)")]
		public string STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this._STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATED_BY", DbType="VarChar(50)")]
		public string UPDATED_BY
		{
			get
			{
				return this._UPDATED_BY;
			}
			set
			{
				if ((this._UPDATED_BY != value))
				{
					this._UPDATED_BY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATED_NAME", DbType="VarChar(43)")]
		public string UPDATED_NAME
		{
			get
			{
				return this._UPDATED_NAME;
			}
			set
			{
				if ((this._UPDATED_NAME != value))
				{
					this._UPDATED_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATED_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> UPDATED_DATE
		{
			get
			{
				return this._UPDATED_DATE;
			}
			set
			{
				if ((this._UPDATED_DATE != value))
				{
					this._UPDATED_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JENIS_PENERIMAAN", DbType="VarChar(50)")]
		public string JENIS_PENERIMAAN
		{
			get
			{
				return this._JENIS_PENERIMAAN;
			}
			set
			{
				if ((this._JENIS_PENERIMAAN != value))
				{
					this._JENIS_PENERIMAAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTIMASI_HARGA", DbType="VarChar(50)")]
		public string ESTIMASI_HARGA
		{
			get
			{
				return this._ESTIMASI_HARGA;
			}
			set
			{
				if ((this._ESTIMASI_HARGA != value))
				{
					this._ESTIMASI_HARGA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEMPAT_PENERIMAAN", DbType="VarChar(50)")]
		public string TEMPAT_PENERIMAAN
		{
			get
			{
				return this._TEMPAT_PENERIMAAN;
			}
			set
			{
				if ((this._TEMPAT_PENERIMAAN != value))
				{
					this._TEMPAT_PENERIMAAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TANGGAL_PENERIMAAN", DbType="DateTime")]
		public System.Nullable<System.DateTime> TANGGAL_PENERIMAAN
		{
			get
			{
				return this._TANGGAL_PENERIMAAN;
			}
			set
			{
				if ((this._TANGGAL_PENERIMAAN != value))
				{
					this._TANGGAL_PENERIMAAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAMA_PEMBERI", DbType="VarChar(50)")]
		public string NAMA_PEMBERI
		{
			get
			{
				return this._NAMA_PEMBERI;
			}
			set
			{
				if ((this._NAMA_PEMBERI != value))
				{
					this._NAMA_PEMBERI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PEKERJAAN_PEMBERI", DbType="VarChar(50)")]
		public string PEKERJAAN_PEMBERI
		{
			get
			{
				return this._PEKERJAAN_PEMBERI;
			}
			set
			{
				if ((this._PEKERJAAN_PEMBERI != value))
				{
					this._PEKERJAAN_PEMBERI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAMA_PERUSAHAAN", DbType="VarChar(50)")]
		public string NAMA_PERUSAHAAN
		{
			get
			{
				return this._NAMA_PERUSAHAAN;
			}
			set
			{
				if ((this._NAMA_PERUSAHAAN != value))
				{
					this._NAMA_PERUSAHAAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HUBUNGAN_PEMBERI", DbType="VarChar(50)")]
		public string HUBUNGAN_PEMBERI
		{
			get
			{
				return this._HUBUNGAN_PEMBERI;
			}
			set
			{
				if ((this._HUBUNGAN_PEMBERI != value))
				{
					this._HUBUNGAN_PEMBERI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ALASAN_PEMBERIAN", DbType="VarChar(MAX)")]
		public string ALASAN_PEMBERIAN
		{
			get
			{
				return this._ALASAN_PEMBERIAN;
			}
			set
			{
				if ((this._ALASAN_PEMBERIAN != value))
				{
					this._ALASAN_PEMBERIAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUKTI_GRATIFIKASI", DbType="VarChar(MAX)")]
		public string BUKTI_GRATIFIKASI
		{
			get
			{
				return this._BUKTI_GRATIFIKASI;
			}
			set
			{
				if ((this._BUKTI_GRATIFIKASI != value))
				{
					this._BUKTI_GRATIFIKASI = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_GRATIFIKASI_REPORT_BOD")]
	public partial class VW_GRATIFIKASI_REPORT_BOD
	{
		
		private int _ID;
		
		private string _NRP;
		
		private string _NAME;
		
		private string _EMAIL;
		
		private string _DEPT;
		
		private string _SITE;
		
		private System.Nullable<System.DateTime> _CREATED_DATE;
		
		private string _STATUS;
		
		private string _UPDATED_BY;
		
		private string _UPDATED_NAME;
		
		private System.Nullable<System.DateTime> _UPDATED_DATE;
		
		private string _JENIS_PENERIMAAN;
		
		private string _ESTIMASI_HARGA;
		
		private string _TEMPAT_PENERIMAAN;
		
		private System.Nullable<System.DateTime> _TANGGAL_PENERIMAAN;
		
		private string _NAMA_PEMBERI;
		
		private string _PEKERJAAN_PEMBERI;
		
		private string _NAMA_PERUSAHAAN;
		
		private string _HUBUNGAN_PEMBERI;
		
		private string _ALASAN_PEMBERIAN;
		
		private string _BUKTI_GRATIFIKASI;
		
		private string _EMPLOYEE_ID;
		
		private string _POSITION_ID;
		
		private string _DSTRCT_CODE;
		
		private string _DEPT_DESC;
		
		private string _Atasan_1;
		
		private string _Atasan_2;
		
		private string _Atasan_3;
		
		private string _Atasan_4;
		
		private string _Atasan_5;
		
		private string _Atasan_6;
		
		private string _Atasan_7;
		
		private string _Atasan_8;
		
		private string _Atasan_9;
		
		private string _Atasan_10;
		
		public VW_GRATIFIKASI_REPORT_BOD()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NRP", DbType="VarChar(50)")]
		public string NRP
		{
			get
			{
				return this._NRP;
			}
			set
			{
				if ((this._NRP != value))
				{
					this._NRP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="VarChar(43)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="NVarChar(4000)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this._EMAIL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT", DbType="VarChar(50)")]
		public string DEPT
		{
			get
			{
				return this._DEPT;
			}
			set
			{
				if ((this._DEPT != value))
				{
					this._DEPT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SITE", DbType="VarChar(50)")]
		public string SITE
		{
			get
			{
				return this._SITE;
			}
			set
			{
				if ((this._SITE != value))
				{
					this._SITE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATED_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATED_DATE
		{
			get
			{
				return this._CREATED_DATE;
			}
			set
			{
				if ((this._CREATED_DATE != value))
				{
					this._CREATED_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="VarChar(50)")]
		public string STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this._STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATED_BY", DbType="VarChar(50)")]
		public string UPDATED_BY
		{
			get
			{
				return this._UPDATED_BY;
			}
			set
			{
				if ((this._UPDATED_BY != value))
				{
					this._UPDATED_BY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATED_NAME", DbType="VarChar(43)")]
		public string UPDATED_NAME
		{
			get
			{
				return this._UPDATED_NAME;
			}
			set
			{
				if ((this._UPDATED_NAME != value))
				{
					this._UPDATED_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATED_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> UPDATED_DATE
		{
			get
			{
				return this._UPDATED_DATE;
			}
			set
			{
				if ((this._UPDATED_DATE != value))
				{
					this._UPDATED_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JENIS_PENERIMAAN", DbType="VarChar(50)")]
		public string JENIS_PENERIMAAN
		{
			get
			{
				return this._JENIS_PENERIMAAN;
			}
			set
			{
				if ((this._JENIS_PENERIMAAN != value))
				{
					this._JENIS_PENERIMAAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTIMASI_HARGA", DbType="VarChar(50)")]
		public string ESTIMASI_HARGA
		{
			get
			{
				return this._ESTIMASI_HARGA;
			}
			set
			{
				if ((this._ESTIMASI_HARGA != value))
				{
					this._ESTIMASI_HARGA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEMPAT_PENERIMAAN", DbType="VarChar(50)")]
		public string TEMPAT_PENERIMAAN
		{
			get
			{
				return this._TEMPAT_PENERIMAAN;
			}
			set
			{
				if ((this._TEMPAT_PENERIMAAN != value))
				{
					this._TEMPAT_PENERIMAAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TANGGAL_PENERIMAAN", DbType="DateTime")]
		public System.Nullable<System.DateTime> TANGGAL_PENERIMAAN
		{
			get
			{
				return this._TANGGAL_PENERIMAAN;
			}
			set
			{
				if ((this._TANGGAL_PENERIMAAN != value))
				{
					this._TANGGAL_PENERIMAAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAMA_PEMBERI", DbType="VarChar(50)")]
		public string NAMA_PEMBERI
		{
			get
			{
				return this._NAMA_PEMBERI;
			}
			set
			{
				if ((this._NAMA_PEMBERI != value))
				{
					this._NAMA_PEMBERI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PEKERJAAN_PEMBERI", DbType="VarChar(50)")]
		public string PEKERJAAN_PEMBERI
		{
			get
			{
				return this._PEKERJAAN_PEMBERI;
			}
			set
			{
				if ((this._PEKERJAAN_PEMBERI != value))
				{
					this._PEKERJAAN_PEMBERI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAMA_PERUSAHAAN", DbType="VarChar(50)")]
		public string NAMA_PERUSAHAAN
		{
			get
			{
				return this._NAMA_PERUSAHAAN;
			}
			set
			{
				if ((this._NAMA_PERUSAHAAN != value))
				{
					this._NAMA_PERUSAHAAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HUBUNGAN_PEMBERI", DbType="VarChar(50)")]
		public string HUBUNGAN_PEMBERI
		{
			get
			{
				return this._HUBUNGAN_PEMBERI;
			}
			set
			{
				if ((this._HUBUNGAN_PEMBERI != value))
				{
					this._HUBUNGAN_PEMBERI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ALASAN_PEMBERIAN", DbType="VarChar(MAX)")]
		public string ALASAN_PEMBERIAN
		{
			get
			{
				return this._ALASAN_PEMBERIAN;
			}
			set
			{
				if ((this._ALASAN_PEMBERIAN != value))
				{
					this._ALASAN_PEMBERIAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUKTI_GRATIFIKASI", DbType="VarChar(MAX)")]
		public string BUKTI_GRATIFIKASI
		{
			get
			{
				return this._BUKTI_GRATIFIKASI;
			}
			set
			{
				if ((this._BUKTI_GRATIFIKASI != value))
				{
					this._BUKTI_GRATIFIKASI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMPLOYEE_ID", DbType="NVarChar(8)")]
		public string EMPLOYEE_ID
		{
			get
			{
				return this._EMPLOYEE_ID;
			}
			set
			{
				if ((this._EMPLOYEE_ID != value))
				{
					this._EMPLOYEE_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSITION_ID", DbType="Char(10)")]
		public string POSITION_ID
		{
			get
			{
				return this._POSITION_ID;
			}
			set
			{
				if ((this._POSITION_ID != value))
				{
					this._POSITION_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSTRCT_CODE", DbType="VarChar(50)")]
		public string DSTRCT_CODE
		{
			get
			{
				return this._DSTRCT_CODE;
			}
			set
			{
				if ((this._DSTRCT_CODE != value))
				{
					this._DSTRCT_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_DESC", DbType="VarChar(100)")]
		public string DEPT_DESC
		{
			get
			{
				return this._DEPT_DESC;
			}
			set
			{
				if ((this._DEPT_DESC != value))
				{
					this._DEPT_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Atasan_1", DbType="NVarChar(10)")]
		public string Atasan_1
		{
			get
			{
				return this._Atasan_1;
			}
			set
			{
				if ((this._Atasan_1 != value))
				{
					this._Atasan_1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Atasan_2", DbType="NVarChar(10)")]
		public string Atasan_2
		{
			get
			{
				return this._Atasan_2;
			}
			set
			{
				if ((this._Atasan_2 != value))
				{
					this._Atasan_2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Atasan_3", DbType="NVarChar(10)")]
		public string Atasan_3
		{
			get
			{
				return this._Atasan_3;
			}
			set
			{
				if ((this._Atasan_3 != value))
				{
					this._Atasan_3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Atasan_4", DbType="NVarChar(10)")]
		public string Atasan_4
		{
			get
			{
				return this._Atasan_4;
			}
			set
			{
				if ((this._Atasan_4 != value))
				{
					this._Atasan_4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Atasan_5", DbType="NVarChar(10)")]
		public string Atasan_5
		{
			get
			{
				return this._Atasan_5;
			}
			set
			{
				if ((this._Atasan_5 != value))
				{
					this._Atasan_5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Atasan_6", DbType="NVarChar(10)")]
		public string Atasan_6
		{
			get
			{
				return this._Atasan_6;
			}
			set
			{
				if ((this._Atasan_6 != value))
				{
					this._Atasan_6 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Atasan_7", DbType="NVarChar(10)")]
		public string Atasan_7
		{
			get
			{
				return this._Atasan_7;
			}
			set
			{
				if ((this._Atasan_7 != value))
				{
					this._Atasan_7 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Atasan_8", DbType="NVarChar(10)")]
		public string Atasan_8
		{
			get
			{
				return this._Atasan_8;
			}
			set
			{
				if ((this._Atasan_8 != value))
				{
					this._Atasan_8 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Atasan_9", DbType="NVarChar(10)")]
		public string Atasan_9
		{
			get
			{
				return this._Atasan_9;
			}
			set
			{
				if ((this._Atasan_9 != value))
				{
					this._Atasan_9 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Atasan_10", DbType="NVarChar(10)")]
		public string Atasan_10
		{
			get
			{
				return this._Atasan_10;
			}
			set
			{
				if ((this._Atasan_10 != value))
				{
					this._Atasan_10 = value;
				}
			}
		}
	}
	
	public partial class cusp_insertNotifProjectManagerResult
	{
		
		private string _TO_LIST;
		
		private string _BODY;
		
		public cusp_insertNotifProjectManagerResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TO_LIST", DbType="VarChar(MAX)")]
		public string TO_LIST
		{
			get
			{
				return this._TO_LIST;
			}
			set
			{
				if ((this._TO_LIST != value))
				{
					this._TO_LIST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BODY", DbType="VarChar(MAX)")]
		public string BODY
		{
			get
			{
				return this._BODY;
			}
			set
			{
				if ((this._BODY != value))
				{
					this._BODY = value;
				}
			}
		}
	}
	
	public partial class cusp_insertNotifDeptHeadResult
	{
		
		private string _TO_LIST;
		
		private string _BODY;
		
		public cusp_insertNotifDeptHeadResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TO_LIST", DbType="VarChar(MAX)")]
		public string TO_LIST
		{
			get
			{
				return this._TO_LIST;
			}
			set
			{
				if ((this._TO_LIST != value))
				{
					this._TO_LIST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BODY", DbType="VarChar(MAX)")]
		public string BODY
		{
			get
			{
				return this._BODY;
			}
			set
			{
				if ((this._BODY != value))
				{
					this._BODY = value;
				}
			}
		}
	}
	
	public partial class cusp_insertNotifBODResult
	{
		
		private string _TO_LIST;
		
		private string _BODY;
		
		public cusp_insertNotifBODResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TO_LIST", DbType="VarChar(MAX)")]
		public string TO_LIST
		{
			get
			{
				return this._TO_LIST;
			}
			set
			{
				if ((this._TO_LIST != value))
				{
					this._TO_LIST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BODY", DbType="VarChar(MAX)")]
		public string BODY
		{
			get
			{
				return this._BODY;
			}
			set
			{
				if ((this._BODY != value))
				{
					this._BODY = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
