<?xml version="1.0" encoding="utf-8"?><Database Name="DB_IA_PAKTA_INTEGRITAS_KPT" Class="DBPakta_IntegritasDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=10.14.101.101\shpol;Initial Catalog=DB_IA_PAKTA_INTEGRITAS_KPT;Persist Security Info=True;User ID=sqlservices" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DB_IA_PAKTA_INTEGRITAS_KPTConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TBL_M_ROLE" Member="TBL_M_ROLEs">
    <Type Name="TBL_M_ROLE">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ROLE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="STATUS" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CREATED_BY" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="CREATED_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UPDATED_BY" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="UPDATED_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_R_USER" Member="TBL_R_USERs">
    <Type Name="TBL_R_USER">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NRP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ROLE" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="STATUS" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CREATED_BY" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="CREATED_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UPDATED_BY" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="UPDATED_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_T_EBEK_FAMILY" Member="TBL_T_EBEK_FAMILies">
    <Type Name="TBL_T_EBEK_FAMILY">
      <Column Name="ID" AutoSync="Never" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EBEK_ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="POSITION" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DEPT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RELATION" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_T_EBEK_MIKAD" Member="TBL_T_EBEK_MIKADs">
    <Type Name="TBL_T_EBEK_MIKAD">
      <Column Name="ID" AutoSync="Never" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EBEK_ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="POSITION" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DEPT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RELATION" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_T_EBEK_COI" Member="TBL_T_EBEK_COIs">
    <Type Name="TBL_T_EBEK_COI">
      <Column Name="ID" AutoSync="Never" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EBEK_ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="CATEGORY" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="COMPANY" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="POSITION" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="INFORMATION" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_T_PI" Member="TBL_T_PIs">
    <Type Name="TBL_T_PI">
      <Column Name="ID" AutoSync="Never" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PI_NO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NRP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SUBMIT" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SIGN_LOCATION" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SUBMITDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_T_EBEK" Member="TBL_T_EBEKs">
    <Type Name="TBL_T_EBEK">
      <Column Name="ID" AutoSync="Never" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EBEK_NO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NRP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SUBMIT" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SIGN_LOCATION" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SUBMITDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ISHADFAMILY" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ISHADMIKAD" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ISHADCOI" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VW_ALL_USER" Member="VW_ALL_USERs">
    <Type Name="VW_ALL_USER">
      <Column Name="EMPLOYEE_ID" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="POSITION_ID" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="POS_TITLE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DSTRCT_CODE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DEPT_CODE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DEPT_DESC" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="alamat" Type="System.String" DbType="VarChar(303)" CanBeNull="true" />
      <Column Name="HIRE_DATE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="GENDER_CODE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="No_telp" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ROLE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PI_SUBMIT" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="EBEK_SUBMIT" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SECTION_HEAD" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VW_EBEK_REPORT" Member="VW_EBEK_REPORTs">
    <Type Name="VW_EBEK_REPORT">
      <Column Name="NRP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SUBMIT" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SIGN_LOCATION" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SUBMITDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ISHADFAMILY" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ISHADMIKAD" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ISHADCOI" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NAME" Type="System.String" DbType="VarChar(43)" CanBeNull="true" />
      <Column Name="DEPT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SITE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VW_PI_REPORT" Member="VW_PI_REPORTs">
    <Type Name="VW_PI_REPORT">
      <Column Name="NRP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SUBMIT" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SIGN_LOCATION" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SUBMITDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NAME" Type="System.String" DbType="VarChar(43)" CanBeNull="true" />
      <Column Name="DEPT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SITE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VW_DEPT_ALL" Member="VW_DEPT_ALLs">
    <Type Name="VW_DEPT_ALL">
      <Column Name="DEPT_CODE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DEPT_DESC" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DEPT_NAME" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VW_DISTRICT_ALL" Member="VW_DISTRICT_ALLs">
    <Type Name="VW_DISTRICT_ALL">
      <Column Name="DSTRCT_CODE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DSTRCT_NAME" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DSTRCT_STATUS" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_T_GRATIFIKASI" Member="TBL_T_GRATIFIKASIs">
    <Type Name="TBL_T_GRATIFIKASI">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NRP" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CREATED_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="STATUS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UPDATED_BY" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UPDATED_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="JENIS_PENERIMAAN" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ESTIMASI_HARGA" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TEMPAT_PENERIMAAN" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TANGGAL_PENERIMAAN" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NAMA_PEMBERI" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PEKERJAAN_PEMBERI" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NAMA_PERUSAHAAN" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HUBUNGAN_PEMBERI" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ALASAN_PEMBERIAN" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="BUKTI_GRATIFIKASI" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VW_GRATIFIKASI_REPORT_BOD" Member="VW_GRATIFIKASI_REPORT_BODs">
    <Type Name="VW_GRATIFIKASI_REPORT_BOD">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NRP" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NAME" Type="System.String" DbType="VarChar(43)" CanBeNull="true" />
      <Column Name="DEPT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SITE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CREATED_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="STATUS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UPDATED_BY" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UPDATED_NAME" Type="System.String" DbType="VarChar(43)" CanBeNull="true" />
      <Column Name="UPDATED_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="JENIS_PENERIMAAN" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ESTIMASI_HARGA" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TEMPAT_PENERIMAAN" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TANGGAL_PENERIMAAN" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NAMA_PEMBERI" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PEKERJAAN_PEMBERI" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NAMA_PERUSAHAAN" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HUBUNGAN_PEMBERI" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ALASAN_PEMBERIAN" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="BUKTI_GRATIFIKASI" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VW_GRATIFIKASI_REPORT_DEPTHEAD" Member="VW_GRATIFIKASI_REPORT_DEPTHEADs">
    <Type Name="VW_GRATIFIKASI_REPORT_DEPTHEAD">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NRP" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NAME" Type="System.String" DbType="VarChar(43)" CanBeNull="true" />
      <Column Name="DEPT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SITE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CREATED_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="STATUS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UPDATED_BY" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UPDATED_NAME" Type="System.String" DbType="VarChar(43)" CanBeNull="true" />
      <Column Name="UPDATED_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="JENIS_PENERIMAAN" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ESTIMASI_HARGA" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TEMPAT_PENERIMAAN" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TANGGAL_PENERIMAAN" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NAMA_PEMBERI" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PEKERJAAN_PEMBERI" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NAMA_PERUSAHAAN" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HUBUNGAN_PEMBERI" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ALASAN_PEMBERIAN" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="BUKTI_GRATIFIKASI" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VW_GRATIFIKASI_REPORT_PM" Member="VW_GRATIFIKASI_REPORT_PMs">
    <Type Name="VW_GRATIFIKASI_REPORT_PM">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NRP" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NAME" Type="System.String" DbType="VarChar(43)" CanBeNull="true" />
      <Column Name="DEPT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SITE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CREATED_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="STATUS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UPDATED_BY" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UPDATED_NAME" Type="System.String" DbType="VarChar(43)" CanBeNull="true" />
      <Column Name="UPDATED_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="JENIS_PENERIMAAN" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ESTIMASI_HARGA" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TEMPAT_PENERIMAAN" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TANGGAL_PENERIMAAN" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NAMA_PEMBERI" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PEKERJAAN_PEMBERI" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NAMA_PERUSAHAAN" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HUBUNGAN_PEMBERI" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ALASAN_PEMBERIAN" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="BUKTI_GRATIFIKASI" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.cusp_insertNotifProjectManager" Method="cusp_insertNotifProjectManager">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <ElementType Name="cusp_insertNotifProjectManagerResult">
      <Column Name="TO_LIST" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="BODY" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.cusp_insertNotifDeptHead" Method="cusp_insertNotifDeptHead">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <ElementType Name="cusp_insertNotifDeptHeadResult">
      <Column Name="TO_LIST" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="BODY" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.cusp_insertNotifBOD" Method="cusp_insertNotifBOD">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <ElementType Name="cusp_insertNotifBODResult">
      <Column Name="TO_LIST" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="BODY" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>