#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INTEGRASI_API_2.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_Surat_KPT")]
	public partial class DBSuratKPTDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTBL_H_LETTER_FAKTA_INTEGRITA(TBL_H_LETTER_FAKTA_INTEGRITA instance);
    partial void UpdateTBL_H_LETTER_FAKTA_INTEGRITA(TBL_H_LETTER_FAKTA_INTEGRITA instance);
    partial void DeleteTBL_H_LETTER_FAKTA_INTEGRITA(TBL_H_LETTER_FAKTA_INTEGRITA instance);
        #endregion

        public DBSuratKPTDataContext() :
		base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DB_Surat_KPTConnectionString"].ConnectionString, mappingSource)
        {
            OnCreated();
        }

        public DBSuratKPTDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBSuratKPTDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBSuratKPTDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBSuratKPTDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<VW_LOGIN_USER> VW_LOGIN_USERs
		{
			get
			{
				return this.GetTable<VW_LOGIN_USER>();
			}
		}
		
		public System.Data.Linq.Table<VW_USER_LOGIN> VW_USER_LOGINs
		{
			get
			{
				return this.GetTable<VW_USER_LOGIN>();
			}
		}
		
		public System.Data.Linq.Table<TBL_H_LETTER_FAKTA_INTEGRITA> TBL_H_LETTER_FAKTA_INTEGRITAs
		{
			get
			{
				return this.GetTable<TBL_H_LETTER_FAKTA_INTEGRITA>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetDataSurat")]
		public ISingleResult<GetDataSuratResult> GetDataSurat([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NRP", DbType="VarChar(50)")] string nRP)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nRP);
			return ((ISingleResult<GetDataSuratResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Getdatasurat_Fakta_integritas")]
		public ISingleResult<Getdatasurat_Fakta_integritasResult> Getdatasurat_Fakta_integritas([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nrp", DbType="VarChar(50)")] string nrp)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nrp);
			return ((ISingleResult<Getdatasurat_Fakta_integritasResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_LOGIN_USER")]
	public partial class VW_LOGIN_USER
	{
		
		private string _EMPLOYEE_ID;
		
		private string _NAME;
		
		private string _POSITION_ID;
		
		private string _POS_TITLE;
		
		private string _dstrct_code;
		
		private string _dept_code;
		
		private string _dept_desc;
		
		public VW_LOGIN_USER()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMPLOYEE_ID", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string EMPLOYEE_ID
		{
			get
			{
				return this._EMPLOYEE_ID;
			}
			set
			{
				if ((this._EMPLOYEE_ID != value))
				{
					this._EMPLOYEE_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="VarChar(100)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSITION_ID", DbType="VarChar(100)")]
		public string POSITION_ID
		{
			get
			{
				return this._POSITION_ID;
			}
			set
			{
				if ((this._POSITION_ID != value))
				{
					this._POSITION_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POS_TITLE", DbType="VarChar(100)")]
		public string POS_TITLE
		{
			get
			{
				return this._POS_TITLE;
			}
			set
			{
				if ((this._POS_TITLE != value))
				{
					this._POS_TITLE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dstrct_code", DbType="VarChar(100)")]
		public string dstrct_code
		{
			get
			{
				return this._dstrct_code;
			}
			set
			{
				if ((this._dstrct_code != value))
				{
					this._dstrct_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dept_code", DbType="VarChar(100)")]
		public string dept_code
		{
			get
			{
				return this._dept_code;
			}
			set
			{
				if ((this._dept_code != value))
				{
					this._dept_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dept_desc", DbType="VarChar(100)")]
		public string dept_desc
		{
			get
			{
				return this._dept_desc;
			}
			set
			{
				if ((this._dept_desc != value))
				{
					this._dept_desc = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_USER_LOGIN")]
	public partial class VW_USER_LOGIN
	{
		
		private string _name;
		
		private string _dept_code;
		
		private string _distrik;
		
		private string _NRP;
		
		private string _password;
		
		private System.Nullable<System.DateTime> _expiredDate;
		
		private string _otp;
		
		private string _token;
		
		private string _device_id;
		
		private System.Nullable<System.DateTime> _loginOTPLockEndDate;
		
		private string _POSITION_ID;
		
		public VW_USER_LOGIN()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(100)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dept_code", DbType="VarChar(100)")]
		public string dept_code
		{
			get
			{
				return this._dept_code;
			}
			set
			{
				if ((this._dept_code != value))
				{
					this._dept_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_distrik", DbType="VarChar(100)")]
		public string distrik
		{
			get
			{
				return this._distrik;
			}
			set
			{
				if ((this._distrik != value))
				{
					this._distrik = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NRP", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NRP
		{
			get
			{
				return this._NRP;
			}
			set
			{
				if ((this._NRP != value))
				{
					this._NRP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(50)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this._password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_expiredDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> expiredDate
		{
			get
			{
				return this._expiredDate;
			}
			set
			{
				if ((this._expiredDate != value))
				{
					this._expiredDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_otp", DbType="VarChar(50)")]
		public string otp
		{
			get
			{
				return this._otp;
			}
			set
			{
				if ((this._otp != value))
				{
					this._otp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_token", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string token
		{
			get
			{
				return this._token;
			}
			set
			{
				if ((this._token != value))
				{
					this._token = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_device_id", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string device_id
		{
			get
			{
				return this._device_id;
			}
			set
			{
				if ((this._device_id != value))
				{
					this._device_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loginOTPLockEndDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> loginOTPLockEndDate
		{
			get
			{
				return this._loginOTPLockEndDate;
			}
			set
			{
				if ((this._loginOTPLockEndDate != value))
				{
					this._loginOTPLockEndDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSITION_ID", DbType="VarChar(100)")]
		public string POSITION_ID
		{
			get
			{
				return this._POSITION_ID;
			}
			set
			{
				if ((this._POSITION_ID != value))
				{
					this._POSITION_ID = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_H_LETTER_FAKTA_INTEGRITAS")]
	public partial class TBL_H_LETTER_FAKTA_INTEGRITA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID;
		
		private string _NO_SURAT;
		
		private string _NRP;
		
		private string _NAME;
		
		private string _POSITION_ID;
		
		private string _DEPT_DESC;
		
		private string _ADDRESS;
		
		private System.Nullable<System.DateTime> _LETTER_DATE;
		
		private System.Nullable<System.DateTime> _CRE_DATE;
		
		private string _CRE_BY;
		
		private System.Nullable<System.DateTime> _MOD_DATE;
		
		private string _MOD_BY;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(long value);
    partial void OnIDChanged();
    partial void OnNO_SURATChanging(string value);
    partial void OnNO_SURATChanged();
    partial void OnNRPChanging(string value);
    partial void OnNRPChanged();
    partial void OnNAMEChanging(string value);
    partial void OnNAMEChanged();
    partial void OnPOSITION_IDChanging(string value);
    partial void OnPOSITION_IDChanged();
    partial void OnDEPT_DESCChanging(string value);
    partial void OnDEPT_DESCChanged();
    partial void OnADDRESSChanging(string value);
    partial void OnADDRESSChanged();
    partial void OnLETTER_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnLETTER_DATEChanged();
    partial void OnCRE_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnCRE_DATEChanged();
    partial void OnCRE_BYChanging(string value);
    partial void OnCRE_BYChanged();
    partial void OnMOD_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnMOD_DATEChanged();
    partial void OnMOD_BYChanging(string value);
    partial void OnMOD_BYChanged();
    #endregion
		
		public TBL_H_LETTER_FAKTA_INTEGRITA()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NO_SURAT", DbType="VarChar(50)")]
		public string NO_SURAT
		{
			get
			{
				return this._NO_SURAT;
			}
			set
			{
				if ((this._NO_SURAT != value))
				{
					this.OnNO_SURATChanging(value);
					this.SendPropertyChanging();
					this._NO_SURAT = value;
					this.SendPropertyChanged("NO_SURAT");
					this.OnNO_SURATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NRP", DbType="VarChar(50)")]
		public string NRP
		{
			get
			{
				return this._NRP;
			}
			set
			{
				if ((this._NRP != value))
				{
					this.OnNRPChanging(value);
					this.SendPropertyChanging();
					this._NRP = value;
					this.SendPropertyChanged("NRP");
					this.OnNRPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="VarChar(255)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this.OnNAMEChanging(value);
					this.SendPropertyChanging();
					this._NAME = value;
					this.SendPropertyChanged("NAME");
					this.OnNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSITION_ID", DbType="VarChar(50)")]
		public string POSITION_ID
		{
			get
			{
				return this._POSITION_ID;
			}
			set
			{
				if ((this._POSITION_ID != value))
				{
					this.OnPOSITION_IDChanging(value);
					this.SendPropertyChanging();
					this._POSITION_ID = value;
					this.SendPropertyChanged("POSITION_ID");
					this.OnPOSITION_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_DESC", DbType="VarChar(100)")]
		public string DEPT_DESC
		{
			get
			{
				return this._DEPT_DESC;
			}
			set
			{
				if ((this._DEPT_DESC != value))
				{
					this.OnDEPT_DESCChanging(value);
					this.SendPropertyChanging();
					this._DEPT_DESC = value;
					this.SendPropertyChanged("DEPT_DESC");
					this.OnDEPT_DESCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDRESS", DbType="NChar(255)")]
		public string ADDRESS
		{
			get
			{
				return this._ADDRESS;
			}
			set
			{
				if ((this._ADDRESS != value))
				{
					this.OnADDRESSChanging(value);
					this.SendPropertyChanging();
					this._ADDRESS = value;
					this.SendPropertyChanged("ADDRESS");
					this.OnADDRESSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LETTER_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> LETTER_DATE
		{
			get
			{
				return this._LETTER_DATE;
			}
			set
			{
				if ((this._LETTER_DATE != value))
				{
					this.OnLETTER_DATEChanging(value);
					this.SendPropertyChanging();
					this._LETTER_DATE = value;
					this.SendPropertyChanged("LETTER_DATE");
					this.OnLETTER_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CRE_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CRE_DATE
		{
			get
			{
				return this._CRE_DATE;
			}
			set
			{
				if ((this._CRE_DATE != value))
				{
					this.OnCRE_DATEChanging(value);
					this.SendPropertyChanging();
					this._CRE_DATE = value;
					this.SendPropertyChanged("CRE_DATE");
					this.OnCRE_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CRE_BY", DbType="VarChar(50)")]
		public string CRE_BY
		{
			get
			{
				return this._CRE_BY;
			}
			set
			{
				if ((this._CRE_BY != value))
				{
					this.OnCRE_BYChanging(value);
					this.SendPropertyChanging();
					this._CRE_BY = value;
					this.SendPropertyChanged("CRE_BY");
					this.OnCRE_BYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MOD_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> MOD_DATE
		{
			get
			{
				return this._MOD_DATE;
			}
			set
			{
				if ((this._MOD_DATE != value))
				{
					this.OnMOD_DATEChanging(value);
					this.SendPropertyChanging();
					this._MOD_DATE = value;
					this.SendPropertyChanged("MOD_DATE");
					this.OnMOD_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MOD_BY", DbType="VarChar(50)")]
		public string MOD_BY
		{
			get
			{
				return this._MOD_BY;
			}
			set
			{
				if ((this._MOD_BY != value))
				{
					this.OnMOD_BYChanging(value);
					this.SendPropertyChanging();
					this._MOD_BY = value;
					this.SendPropertyChanged("MOD_BY");
					this.OnMOD_BYChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class GetDataSuratResult
	{
		
		private string _EMPLOYEE_ID;
		
		private string _FIRST_NAME;
		
		private string _SURNAME;
		
		private string _NAME;
		
		private string _POSITION_ID;
		
		private string _POS_TITLE;
		
		private string _CHANGE_REASON;
		
		private string _CHANGE_REASON_DESC;
		
		private string _DSTRCT_CODE;
		
		private string _WORK_LOC;
		
		private string _WORK_LOC_DESC;
		
		private string _EMP_STATUS;
		
		private string _EMP_STATUS_DESC;
		
		private string _GENDER_CODE;
		
		private string _GENDER_DESC;
		
		private string _EMP_TYPE;
		
		private string _EMP_TYPE_DESC;
		
		private string _STAFF_CATEG;
		
		private string _STAFF_CATEG_DESC;
		
		private string _BIRTH_DATE;
		
		private string _HIRE_DATE;
		
		private string _SERVICE_DATE;
		
		private string _TERMINATION_DATE;
		
		private string _DEPT_CODE_OLD;
		
		private string _DEPT_CODE_OLD_DESC;
		
		private string _STATUS_HIRE;
		
		private string _STATUS_HIRE_DESC;
		
		private string _POINT_OF_HIRE;
		
		private string _POINT_OF_HIRE_DESC;
		
		private string _ACCOUNT_DOMAIN;
		
		private string _NRP;
		
		private string _AGE;
		
		private string _BLOOD_TYPE;
		
		private string _RELIGION_DESC;
		
		private string _RES_ADDRESS_1;
		
		private string _RES_ADDRESS_2;
		
		private string _RES_ADDRESS_3;
		
		private string _RES_ZIPCODE;
		
		private string _SUPERIOR_ID;
		
		private string _POSITION_START_DATE;
		
		private string _GOLONGAN;
		
		private string _GOL_COMPTCY_LEVEL;
		
		private string _GOL_START_DATE;
		
		private string _HOME_PHONE_NO;
		
		private string _HOME_MOBILE_NO;
		
		private string _RANKS;
		
		private string _RANK_DESC;
		
		private string _RANK_START_DATE;
		
		private string _DEPT_CODE;
		
		private string _DEPT_DESC;
		
		private string _DIV_CODE;
		
		private string _DIV_DESC;
		
		private string _Address_LotusNotes;
		
		private string _Email_Internet;
		
		private string _ACTIVE_STATUS;
		
		private string _DEPT_CODE_DESC;
		
		private string _DIV_CODE_DESC;
		
		private string _DEPT_CODE_PERS;
		
		private string _DEPT_CODE_PERS_DESC;
		
		private string _GENDER;
		
		private string _NAME_INITCAP;
		
		private string _RELIGION;
		
		private string _MODIFIED_DATE;
		
		private string _RANKS_DESC;
		
		private string _RANKS_START_DATE;
		
		private string _SECONDARY_POSITION_ID;
		
		private string _LAST_EDUCATION;
		
		private string _BIRTH_PLACE;
		
		private string _BIRTH_PLACE_DESC;
		
		private string _GROUP_GOLONGAN;
		
		private string _MARITAL_STATUS;
		
		private string _MARITAL_STATUS_DESC;
		
		private string _JURUSAN;
		
		private string _UNIVERSITAS;
		
		private string _LAST_EDU_TIMESTAMP_ELLIPSE;
		
		public GetDataSuratResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMPLOYEE_ID", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string EMPLOYEE_ID
		{
			get
			{
				return this._EMPLOYEE_ID;
			}
			set
			{
				if ((this._EMPLOYEE_ID != value))
				{
					this._EMPLOYEE_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIRST_NAME", DbType="VarChar(100)")]
		public string FIRST_NAME
		{
			get
			{
				return this._FIRST_NAME;
			}
			set
			{
				if ((this._FIRST_NAME != value))
				{
					this._FIRST_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SURNAME", DbType="VarChar(100)")]
		public string SURNAME
		{
			get
			{
				return this._SURNAME;
			}
			set
			{
				if ((this._SURNAME != value))
				{
					this._SURNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="VarChar(100)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSITION_ID", DbType="VarChar(100)")]
		public string POSITION_ID
		{
			get
			{
				return this._POSITION_ID;
			}
			set
			{
				if ((this._POSITION_ID != value))
				{
					this._POSITION_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POS_TITLE", DbType="VarChar(100)")]
		public string POS_TITLE
		{
			get
			{
				return this._POS_TITLE;
			}
			set
			{
				if ((this._POS_TITLE != value))
				{
					this._POS_TITLE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHANGE_REASON", DbType="VarChar(100)")]
		public string CHANGE_REASON
		{
			get
			{
				return this._CHANGE_REASON;
			}
			set
			{
				if ((this._CHANGE_REASON != value))
				{
					this._CHANGE_REASON = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHANGE_REASON_DESC", DbType="VarChar(100)")]
		public string CHANGE_REASON_DESC
		{
			get
			{
				return this._CHANGE_REASON_DESC;
			}
			set
			{
				if ((this._CHANGE_REASON_DESC != value))
				{
					this._CHANGE_REASON_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSTRCT_CODE", DbType="VarChar(100)")]
		public string DSTRCT_CODE
		{
			get
			{
				return this._DSTRCT_CODE;
			}
			set
			{
				if ((this._DSTRCT_CODE != value))
				{
					this._DSTRCT_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WORK_LOC", DbType="VarChar(100)")]
		public string WORK_LOC
		{
			get
			{
				return this._WORK_LOC;
			}
			set
			{
				if ((this._WORK_LOC != value))
				{
					this._WORK_LOC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WORK_LOC_DESC", DbType="VarChar(100)")]
		public string WORK_LOC_DESC
		{
			get
			{
				return this._WORK_LOC_DESC;
			}
			set
			{
				if ((this._WORK_LOC_DESC != value))
				{
					this._WORK_LOC_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_STATUS", DbType="VarChar(100)")]
		public string EMP_STATUS
		{
			get
			{
				return this._EMP_STATUS;
			}
			set
			{
				if ((this._EMP_STATUS != value))
				{
					this._EMP_STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_STATUS_DESC", DbType="VarChar(100)")]
		public string EMP_STATUS_DESC
		{
			get
			{
				return this._EMP_STATUS_DESC;
			}
			set
			{
				if ((this._EMP_STATUS_DESC != value))
				{
					this._EMP_STATUS_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GENDER_CODE", DbType="VarChar(100)")]
		public string GENDER_CODE
		{
			get
			{
				return this._GENDER_CODE;
			}
			set
			{
				if ((this._GENDER_CODE != value))
				{
					this._GENDER_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GENDER_DESC", DbType="VarChar(100)")]
		public string GENDER_DESC
		{
			get
			{
				return this._GENDER_DESC;
			}
			set
			{
				if ((this._GENDER_DESC != value))
				{
					this._GENDER_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_TYPE", DbType="VarChar(100)")]
		public string EMP_TYPE
		{
			get
			{
				return this._EMP_TYPE;
			}
			set
			{
				if ((this._EMP_TYPE != value))
				{
					this._EMP_TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_TYPE_DESC", DbType="VarChar(100)")]
		public string EMP_TYPE_DESC
		{
			get
			{
				return this._EMP_TYPE_DESC;
			}
			set
			{
				if ((this._EMP_TYPE_DESC != value))
				{
					this._EMP_TYPE_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STAFF_CATEG", DbType="VarChar(100)")]
		public string STAFF_CATEG
		{
			get
			{
				return this._STAFF_CATEG;
			}
			set
			{
				if ((this._STAFF_CATEG != value))
				{
					this._STAFF_CATEG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STAFF_CATEG_DESC", DbType="VarChar(100)")]
		public string STAFF_CATEG_DESC
		{
			get
			{
				return this._STAFF_CATEG_DESC;
			}
			set
			{
				if ((this._STAFF_CATEG_DESC != value))
				{
					this._STAFF_CATEG_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BIRTH_DATE", DbType="VarChar(100)")]
		public string BIRTH_DATE
		{
			get
			{
				return this._BIRTH_DATE;
			}
			set
			{
				if ((this._BIRTH_DATE != value))
				{
					this._BIRTH_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HIRE_DATE", DbType="VarChar(100)")]
		public string HIRE_DATE
		{
			get
			{
				return this._HIRE_DATE;
			}
			set
			{
				if ((this._HIRE_DATE != value))
				{
					this._HIRE_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SERVICE_DATE", DbType="VarChar(100)")]
		public string SERVICE_DATE
		{
			get
			{
				return this._SERVICE_DATE;
			}
			set
			{
				if ((this._SERVICE_DATE != value))
				{
					this._SERVICE_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TERMINATION_DATE", DbType="VarChar(100)")]
		public string TERMINATION_DATE
		{
			get
			{
				return this._TERMINATION_DATE;
			}
			set
			{
				if ((this._TERMINATION_DATE != value))
				{
					this._TERMINATION_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_CODE_OLD", DbType="VarChar(100)")]
		public string DEPT_CODE_OLD
		{
			get
			{
				return this._DEPT_CODE_OLD;
			}
			set
			{
				if ((this._DEPT_CODE_OLD != value))
				{
					this._DEPT_CODE_OLD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_CODE_OLD_DESC", DbType="VarChar(100)")]
		public string DEPT_CODE_OLD_DESC
		{
			get
			{
				return this._DEPT_CODE_OLD_DESC;
			}
			set
			{
				if ((this._DEPT_CODE_OLD_DESC != value))
				{
					this._DEPT_CODE_OLD_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS_HIRE", DbType="VarChar(100)")]
		public string STATUS_HIRE
		{
			get
			{
				return this._STATUS_HIRE;
			}
			set
			{
				if ((this._STATUS_HIRE != value))
				{
					this._STATUS_HIRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS_HIRE_DESC", DbType="VarChar(100)")]
		public string STATUS_HIRE_DESC
		{
			get
			{
				return this._STATUS_HIRE_DESC;
			}
			set
			{
				if ((this._STATUS_HIRE_DESC != value))
				{
					this._STATUS_HIRE_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POINT_OF_HIRE", DbType="VarChar(100)")]
		public string POINT_OF_HIRE
		{
			get
			{
				return this._POINT_OF_HIRE;
			}
			set
			{
				if ((this._POINT_OF_HIRE != value))
				{
					this._POINT_OF_HIRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POINT_OF_HIRE_DESC", DbType="VarChar(100)")]
		public string POINT_OF_HIRE_DESC
		{
			get
			{
				return this._POINT_OF_HIRE_DESC;
			}
			set
			{
				if ((this._POINT_OF_HIRE_DESC != value))
				{
					this._POINT_OF_HIRE_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACCOUNT_DOMAIN", DbType="VarChar(100)")]
		public string ACCOUNT_DOMAIN
		{
			get
			{
				return this._ACCOUNT_DOMAIN;
			}
			set
			{
				if ((this._ACCOUNT_DOMAIN != value))
				{
					this._ACCOUNT_DOMAIN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NRP", DbType="VarChar(100)")]
		public string NRP
		{
			get
			{
				return this._NRP;
			}
			set
			{
				if ((this._NRP != value))
				{
					this._NRP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AGE", DbType="VarChar(100)")]
		public string AGE
		{
			get
			{
				return this._AGE;
			}
			set
			{
				if ((this._AGE != value))
				{
					this._AGE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BLOOD_TYPE", DbType="VarChar(100)")]
		public string BLOOD_TYPE
		{
			get
			{
				return this._BLOOD_TYPE;
			}
			set
			{
				if ((this._BLOOD_TYPE != value))
				{
					this._BLOOD_TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RELIGION_DESC", DbType="VarChar(100)")]
		public string RELIGION_DESC
		{
			get
			{
				return this._RELIGION_DESC;
			}
			set
			{
				if ((this._RELIGION_DESC != value))
				{
					this._RELIGION_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RES_ADDRESS_1", DbType="VarChar(100)")]
		public string RES_ADDRESS_1
		{
			get
			{
				return this._RES_ADDRESS_1;
			}
			set
			{
				if ((this._RES_ADDRESS_1 != value))
				{
					this._RES_ADDRESS_1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RES_ADDRESS_2", DbType="VarChar(100)")]
		public string RES_ADDRESS_2
		{
			get
			{
				return this._RES_ADDRESS_2;
			}
			set
			{
				if ((this._RES_ADDRESS_2 != value))
				{
					this._RES_ADDRESS_2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RES_ADDRESS_3", DbType="VarChar(100)")]
		public string RES_ADDRESS_3
		{
			get
			{
				return this._RES_ADDRESS_3;
			}
			set
			{
				if ((this._RES_ADDRESS_3 != value))
				{
					this._RES_ADDRESS_3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RES_ZIPCODE", DbType="VarChar(100)")]
		public string RES_ZIPCODE
		{
			get
			{
				return this._RES_ZIPCODE;
			}
			set
			{
				if ((this._RES_ZIPCODE != value))
				{
					this._RES_ZIPCODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUPERIOR_ID", DbType="VarChar(100)")]
		public string SUPERIOR_ID
		{
			get
			{
				return this._SUPERIOR_ID;
			}
			set
			{
				if ((this._SUPERIOR_ID != value))
				{
					this._SUPERIOR_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSITION_START_DATE", DbType="VarChar(100)")]
		public string POSITION_START_DATE
		{
			get
			{
				return this._POSITION_START_DATE;
			}
			set
			{
				if ((this._POSITION_START_DATE != value))
				{
					this._POSITION_START_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GOLONGAN", DbType="VarChar(100)")]
		public string GOLONGAN
		{
			get
			{
				return this._GOLONGAN;
			}
			set
			{
				if ((this._GOLONGAN != value))
				{
					this._GOLONGAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GOL_COMPTCY_LEVEL", DbType="VarChar(100)")]
		public string GOL_COMPTCY_LEVEL
		{
			get
			{
				return this._GOL_COMPTCY_LEVEL;
			}
			set
			{
				if ((this._GOL_COMPTCY_LEVEL != value))
				{
					this._GOL_COMPTCY_LEVEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GOL_START_DATE", DbType="VarChar(100)")]
		public string GOL_START_DATE
		{
			get
			{
				return this._GOL_START_DATE;
			}
			set
			{
				if ((this._GOL_START_DATE != value))
				{
					this._GOL_START_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOME_PHONE_NO", DbType="VarChar(100)")]
		public string HOME_PHONE_NO
		{
			get
			{
				return this._HOME_PHONE_NO;
			}
			set
			{
				if ((this._HOME_PHONE_NO != value))
				{
					this._HOME_PHONE_NO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOME_MOBILE_NO", DbType="VarChar(100)")]
		public string HOME_MOBILE_NO
		{
			get
			{
				return this._HOME_MOBILE_NO;
			}
			set
			{
				if ((this._HOME_MOBILE_NO != value))
				{
					this._HOME_MOBILE_NO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RANKS", DbType="VarChar(100)")]
		public string RANKS
		{
			get
			{
				return this._RANKS;
			}
			set
			{
				if ((this._RANKS != value))
				{
					this._RANKS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RANK_DESC", DbType="VarChar(100)")]
		public string RANK_DESC
		{
			get
			{
				return this._RANK_DESC;
			}
			set
			{
				if ((this._RANK_DESC != value))
				{
					this._RANK_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RANK_START_DATE", DbType="VarChar(100)")]
		public string RANK_START_DATE
		{
			get
			{
				return this._RANK_START_DATE;
			}
			set
			{
				if ((this._RANK_START_DATE != value))
				{
					this._RANK_START_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_CODE", DbType="VarChar(100)")]
		public string DEPT_CODE
		{
			get
			{
				return this._DEPT_CODE;
			}
			set
			{
				if ((this._DEPT_CODE != value))
				{
					this._DEPT_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_DESC", DbType="VarChar(100)")]
		public string DEPT_DESC
		{
			get
			{
				return this._DEPT_DESC;
			}
			set
			{
				if ((this._DEPT_DESC != value))
				{
					this._DEPT_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIV_CODE", DbType="VarChar(100)")]
		public string DIV_CODE
		{
			get
			{
				return this._DIV_CODE;
			}
			set
			{
				if ((this._DIV_CODE != value))
				{
					this._DIV_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIV_DESC", DbType="VarChar(100)")]
		public string DIV_DESC
		{
			get
			{
				return this._DIV_DESC;
			}
			set
			{
				if ((this._DIV_DESC != value))
				{
					this._DIV_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address_LotusNotes", DbType="VarChar(100)")]
		public string Address_LotusNotes
		{
			get
			{
				return this._Address_LotusNotes;
			}
			set
			{
				if ((this._Address_LotusNotes != value))
				{
					this._Address_LotusNotes = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email_Internet", DbType="VarChar(100)")]
		public string Email_Internet
		{
			get
			{
				return this._Email_Internet;
			}
			set
			{
				if ((this._Email_Internet != value))
				{
					this._Email_Internet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACTIVE_STATUS", DbType="VarChar(100)")]
		public string ACTIVE_STATUS
		{
			get
			{
				return this._ACTIVE_STATUS;
			}
			set
			{
				if ((this._ACTIVE_STATUS != value))
				{
					this._ACTIVE_STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_CODE_DESC", DbType="VarChar(100)")]
		public string DEPT_CODE_DESC
		{
			get
			{
				return this._DEPT_CODE_DESC;
			}
			set
			{
				if ((this._DEPT_CODE_DESC != value))
				{
					this._DEPT_CODE_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIV_CODE_DESC", DbType="VarChar(100)")]
		public string DIV_CODE_DESC
		{
			get
			{
				return this._DIV_CODE_DESC;
			}
			set
			{
				if ((this._DIV_CODE_DESC != value))
				{
					this._DIV_CODE_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_CODE_PERS", DbType="VarChar(100)")]
		public string DEPT_CODE_PERS
		{
			get
			{
				return this._DEPT_CODE_PERS;
			}
			set
			{
				if ((this._DEPT_CODE_PERS != value))
				{
					this._DEPT_CODE_PERS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_CODE_PERS_DESC", DbType="VarChar(100)")]
		public string DEPT_CODE_PERS_DESC
		{
			get
			{
				return this._DEPT_CODE_PERS_DESC;
			}
			set
			{
				if ((this._DEPT_CODE_PERS_DESC != value))
				{
					this._DEPT_CODE_PERS_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GENDER", DbType="VarChar(100)")]
		public string GENDER
		{
			get
			{
				return this._GENDER;
			}
			set
			{
				if ((this._GENDER != value))
				{
					this._GENDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME_INITCAP", DbType="VarChar(100)")]
		public string NAME_INITCAP
		{
			get
			{
				return this._NAME_INITCAP;
			}
			set
			{
				if ((this._NAME_INITCAP != value))
				{
					this._NAME_INITCAP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RELIGION", DbType="VarChar(100)")]
		public string RELIGION
		{
			get
			{
				return this._RELIGION;
			}
			set
			{
				if ((this._RELIGION != value))
				{
					this._RELIGION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODIFIED_DATE", DbType="VarChar(100)")]
		public string MODIFIED_DATE
		{
			get
			{
				return this._MODIFIED_DATE;
			}
			set
			{
				if ((this._MODIFIED_DATE != value))
				{
					this._MODIFIED_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RANKS_DESC", DbType="VarChar(100)")]
		public string RANKS_DESC
		{
			get
			{
				return this._RANKS_DESC;
			}
			set
			{
				if ((this._RANKS_DESC != value))
				{
					this._RANKS_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RANKS_START_DATE", DbType="VarChar(100)")]
		public string RANKS_START_DATE
		{
			get
			{
				return this._RANKS_START_DATE;
			}
			set
			{
				if ((this._RANKS_START_DATE != value))
				{
					this._RANKS_START_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SECONDARY_POSITION_ID", DbType="VarChar(100)")]
		public string SECONDARY_POSITION_ID
		{
			get
			{
				return this._SECONDARY_POSITION_ID;
			}
			set
			{
				if ((this._SECONDARY_POSITION_ID != value))
				{
					this._SECONDARY_POSITION_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_EDUCATION", DbType="VarChar(100)")]
		public string LAST_EDUCATION
		{
			get
			{
				return this._LAST_EDUCATION;
			}
			set
			{
				if ((this._LAST_EDUCATION != value))
				{
					this._LAST_EDUCATION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BIRTH_PLACE", DbType="VarChar(100)")]
		public string BIRTH_PLACE
		{
			get
			{
				return this._BIRTH_PLACE;
			}
			set
			{
				if ((this._BIRTH_PLACE != value))
				{
					this._BIRTH_PLACE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BIRTH_PLACE_DESC", DbType="VarChar(100)")]
		public string BIRTH_PLACE_DESC
		{
			get
			{
				return this._BIRTH_PLACE_DESC;
			}
			set
			{
				if ((this._BIRTH_PLACE_DESC != value))
				{
					this._BIRTH_PLACE_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GROUP_GOLONGAN", DbType="VarChar(100)")]
		public string GROUP_GOLONGAN
		{
			get
			{
				return this._GROUP_GOLONGAN;
			}
			set
			{
				if ((this._GROUP_GOLONGAN != value))
				{
					this._GROUP_GOLONGAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MARITAL_STATUS", DbType="VarChar(100)")]
		public string MARITAL_STATUS
		{
			get
			{
				return this._MARITAL_STATUS;
			}
			set
			{
				if ((this._MARITAL_STATUS != value))
				{
					this._MARITAL_STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MARITAL_STATUS_DESC", DbType="VarChar(100)")]
		public string MARITAL_STATUS_DESC
		{
			get
			{
				return this._MARITAL_STATUS_DESC;
			}
			set
			{
				if ((this._MARITAL_STATUS_DESC != value))
				{
					this._MARITAL_STATUS_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JURUSAN", DbType="VarChar(100)")]
		public string JURUSAN
		{
			get
			{
				return this._JURUSAN;
			}
			set
			{
				if ((this._JURUSAN != value))
				{
					this._JURUSAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UNIVERSITAS", DbType="VarChar(100)")]
		public string UNIVERSITAS
		{
			get
			{
				return this._UNIVERSITAS;
			}
			set
			{
				if ((this._UNIVERSITAS != value))
				{
					this._UNIVERSITAS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_EDU_TIMESTAMP_ELLIPSE", DbType="VarChar(100)")]
		public string LAST_EDU_TIMESTAMP_ELLIPSE
		{
			get
			{
				return this._LAST_EDU_TIMESTAMP_ELLIPSE;
			}
			set
			{
				if ((this._LAST_EDU_TIMESTAMP_ELLIPSE != value))
				{
					this._LAST_EDU_TIMESTAMP_ELLIPSE = value;
				}
			}
		}
	}
	
	public partial class Getdatasurat_Fakta_integritasResult
	{
		
		private string _NO_SURAT;
		
		private string _NRP;
		
		private string _NAME;
		
		private string _POSITION_ID;
		
		private string _DEPT_DESC;
		
		private string _Address;
		
		private System.DateTime _LETTER_DATE;
		
		private System.DateTime _CRE_DATE;
		
		private string _CRE_BY;
		
		private System.Nullable<int> _MOD_DATE;
		
		private System.Nullable<int> _MOD_BY;
		
		public Getdatasurat_Fakta_integritasResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NO_SURAT", DbType="VarChar(30)")]
		public string NO_SURAT
		{
			get
			{
				return this._NO_SURAT;
			}
			set
			{
				if ((this._NO_SURAT != value))
				{
					this._NO_SURAT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NRP", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string NRP
		{
			get
			{
				return this._NRP;
			}
			set
			{
				if ((this._NRP != value))
				{
					this._NRP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="VarChar(100)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSITION_ID", DbType="VarChar(100)")]
		public string POSITION_ID
		{
			get
			{
				return this._POSITION_ID;
			}
			set
			{
				if ((this._POSITION_ID != value))
				{
					this._POSITION_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_DESC", DbType="VarChar(100)")]
		public string DEPT_DESC
		{
			get
			{
				return this._DEPT_DESC;
			}
			set
			{
				if ((this._DEPT_DESC != value))
				{
					this._DEPT_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(100)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this._Address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LETTER_DATE", DbType="DateTime NOT NULL")]
		public System.DateTime LETTER_DATE
		{
			get
			{
				return this._LETTER_DATE;
			}
			set
			{
				if ((this._LETTER_DATE != value))
				{
					this._LETTER_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CRE_DATE", DbType="DateTime NOT NULL")]
		public System.DateTime CRE_DATE
		{
			get
			{
				return this._CRE_DATE;
			}
			set
			{
				if ((this._CRE_DATE != value))
				{
					this._CRE_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CRE_BY", DbType="VarChar(50)")]
		public string CRE_BY
		{
			get
			{
				return this._CRE_BY;
			}
			set
			{
				if ((this._CRE_BY != value))
				{
					this._CRE_BY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MOD_DATE", DbType="Int")]
		public System.Nullable<int> MOD_DATE
		{
			get
			{
				return this._MOD_DATE;
			}
			set
			{
				if ((this._MOD_DATE != value))
				{
					this._MOD_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MOD_BY", DbType="Int")]
		public System.Nullable<int> MOD_BY
		{
			get
			{
				return this._MOD_BY;
			}
			set
			{
				if ((this._MOD_BY != value))
				{
					this._MOD_BY = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
